import { MetaPage } from "@/spaces/meta/MetaPage";
import type { MatchupData } from "@/spaces/meta/types";

export const dynamicParams = false;
export const dynamic = "force-static";
export const fetchCache = "force-cache";

const matchups: MatchupData[] = [
  {
    deck: "amber/amethyst",
    versus: "amber/steel",
    total_matches: "1297",
    wins: "322",
    overall_winrate: "24.83",
    wins_on_play: "197",
    matches_on_play: "665",
    play_winrate: "29.62",
    wins_on_draw: "125",
    matches_on_draw: "632",
    draw_winrate: "19.78",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/ruby",
    total_matches: "1173",
    wins: "631",
    overall_winrate: "53.79",
    wins_on_play: "361",
    matches_on_play: "584",
    play_winrate: "61.82",
    wins_on_draw: "270",
    matches_on_draw: "589",
    draw_winrate: "45.84",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/sapphire",
    total_matches: "1108",
    wins: "687",
    overall_winrate: "62.00",
    wins_on_play: "394",
    matches_on_play: "548",
    play_winrate: "71.90",
    wins_on_draw: "293",
    matches_on_draw: "560",
    draw_winrate: "52.32",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/steel",
    total_matches: "845",
    wins: "307",
    overall_winrate: "36.33",
    wins_on_play: "190",
    matches_on_play: "427",
    play_winrate: "44.50",
    wins_on_draw: "117",
    matches_on_draw: "418",
    draw_winrate: "27.99",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/emerald",
    total_matches: "728",
    wins: "304",
    overall_winrate: "41.76",
    wins_on_play: "191",
    matches_on_play: "372",
    play_winrate: "51.34",
    wins_on_draw: "113",
    matches_on_draw: "356",
    draw_winrate: "31.74",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "sapphire/steel",
    total_matches: "591",
    wins: "290",
    overall_winrate: "49.07",
    wins_on_play: "171",
    matches_on_play: "303",
    play_winrate: "56.44",
    wins_on_draw: "119",
    matches_on_draw: "288",
    draw_winrate: "41.32",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "steel/emerald",
    total_matches: "546",
    wins: "159",
    overall_winrate: "29.12",
    wins_on_play: "97",
    matches_on_play: "257",
    play_winrate: "37.74",
    wins_on_draw: "62",
    matches_on_draw: "289",
    draw_winrate: "21.45",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/sapphire",
    total_matches: "424",
    wins: "214",
    overall_winrate: "50.47",
    wins_on_play: "131",
    matches_on_play: "212",
    play_winrate: "61.79",
    wins_on_draw: "83",
    matches_on_draw: "212",
    draw_winrate: "39.15",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "sapphire/emerald",
    total_matches: "234",
    wins: "132",
    overall_winrate: "56.41",
    wins_on_play: "73",
    matches_on_play: "114",
    play_winrate: "64.04",
    wins_on_draw: "59",
    matches_on_draw: "120",
    draw_winrate: "49.17",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/ruby",
    total_matches: "189",
    wins: "91",
    overall_winrate: "48.15",
    wins_on_play: "51",
    matches_on_play: "94",
    play_winrate: "54.26",
    wins_on_draw: "40",
    matches_on_draw: "95",
    draw_winrate: "42.11",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/amethyst",
    total_matches: "155",
    wins: "155",
    overall_winrate: "100.00",
    wins_on_play: "132",
    matches_on_play: "132",
    play_winrate: "100.00",
    wins_on_draw: "124",
    matches_on_draw: "124",
    draw_winrate: "100.00",
    mirror_matches: "155",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/steel",
    total_matches: "126",
    wins: "45",
    overall_winrate: "35.71",
    wins_on_play: "21",
    matches_on_play: "51",
    play_winrate: "41.18",
    wins_on_draw: "24",
    matches_on_draw: "75",
    draw_winrate: "32.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/emerald",
    total_matches: "125",
    wins: "63",
    overall_winrate: "50.40",
    wins_on_play: "41",
    matches_on_play: "67",
    play_winrate: "61.19",
    wins_on_draw: "22",
    matches_on_draw: "58",
    draw_winrate: "37.93",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/emerald",
    total_matches: "65",
    wins: "37",
    overall_winrate: "56.92",
    wins_on_play: "18",
    matches_on_play: "27",
    play_winrate: "66.67",
    wins_on_draw: "19",
    matches_on_draw: "38",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/sapphire",
    total_matches: "57",
    wins: "32",
    overall_winrate: "56.14",
    wins_on_play: "19",
    matches_on_play: "30",
    play_winrate: "63.33",
    wins_on_draw: "13",
    matches_on_draw: "27",
    draw_winrate: "48.15",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/steel",
    total_matches: "1381",
    wins: "436",
    overall_winrate: "31.57",
    wins_on_play: "257",
    matches_on_play: "671",
    play_winrate: "38.30",
    wins_on_draw: "179",
    matches_on_draw: "710",
    draw_winrate: "25.21",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/sapphire",
    total_matches: "1269",
    wins: "662",
    overall_winrate: "52.17",
    wins_on_play: "379",
    matches_on_play: "633",
    play_winrate: "59.87",
    wins_on_draw: "283",
    matches_on_draw: "636",
    draw_winrate: "44.50",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/ruby",
    total_matches: "1241",
    wins: "582",
    overall_winrate: "46.90",
    wins_on_play: "338",
    matches_on_play: "619",
    play_winrate: "54.60",
    wins_on_draw: "244",
    matches_on_draw: "622",
    draw_winrate: "39.23",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/steel",
    total_matches: "939",
    wins: "356",
    overall_winrate: "37.91",
    wins_on_play: "199",
    matches_on_play: "482",
    play_winrate: "41.29",
    wins_on_draw: "157",
    matches_on_draw: "457",
    draw_winrate: "34.35",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/emerald",
    total_matches: "824",
    wins: "343",
    overall_winrate: "41.63",
    wins_on_play: "227",
    matches_on_play: "443",
    play_winrate: "51.24",
    wins_on_draw: "116",
    matches_on_draw: "381",
    draw_winrate: "30.45",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "steel/emerald",
    total_matches: "623",
    wins: "222",
    overall_winrate: "35.63",
    wins_on_play: "128",
    matches_on_play: "297",
    play_winrate: "43.10",
    wins_on_draw: "94",
    matches_on_draw: "326",
    draw_winrate: "28.83",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "sapphire/steel",
    total_matches: "613",
    wins: "272",
    overall_winrate: "44.37",
    wins_on_play: "157",
    matches_on_play: "302",
    play_winrate: "51.99",
    wins_on_draw: "115",
    matches_on_draw: "311",
    draw_winrate: "36.98",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/sapphire",
    total_matches: "498",
    wins: "254",
    overall_winrate: "51.00",
    wins_on_play: "146",
    matches_on_play: "240",
    play_winrate: "60.83",
    wins_on_draw: "108",
    matches_on_draw: "258",
    draw_winrate: "41.86",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "sapphire/emerald",
    total_matches: "276",
    wins: "187",
    overall_winrate: "67.75",
    wins_on_play: "106",
    matches_on_play: "143",
    play_winrate: "74.13",
    wins_on_draw: "81",
    matches_on_draw: "133",
    draw_winrate: "60.90",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/ruby",
    total_matches: "203",
    wins: "116",
    overall_winrate: "57.14",
    wins_on_play: "73",
    matches_on_play: "114",
    play_winrate: "64.04",
    wins_on_draw: "43",
    matches_on_draw: "89",
    draw_winrate: "48.31",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/emerald",
    total_matches: "174",
    wins: "174",
    overall_winrate: "100.00",
    wins_on_play: "149",
    matches_on_play: "149",
    play_winrate: "100.00",
    wins_on_draw: "129",
    matches_on_draw: "129",
    draw_winrate: "100.00",
    mirror_matches: "174",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/steel",
    total_matches: "132",
    wins: "55",
    overall_winrate: "41.67",
    wins_on_play: "28",
    matches_on_play: "66",
    play_winrate: "42.42",
    wins_on_draw: "27",
    matches_on_draw: "66",
    draw_winrate: "40.91",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/amethyst",
    total_matches: "125",
    wins: "62",
    overall_winrate: "49.60",
    wins_on_play: "36",
    matches_on_play: "58",
    play_winrate: "62.07",
    wins_on_draw: "26",
    matches_on_draw: "67",
    draw_winrate: "38.81",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/emerald",
    total_matches: "72",
    wins: "40",
    overall_winrate: "55.56",
    wins_on_play: "22",
    matches_on_play: "36",
    play_winrate: "61.11",
    wins_on_draw: "18",
    matches_on_draw: "36",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/sapphire",
    total_matches: "41",
    wins: "26",
    overall_winrate: "63.41",
    wins_on_play: "14",
    matches_on_play: "23",
    play_winrate: "60.87",
    wins_on_draw: "12",
    matches_on_draw: "18",
    draw_winrate: "66.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/steel",
    total_matches: "1815",
    wins: "583",
    overall_winrate: "32.12",
    wins_on_play: "330",
    matches_on_play: "877",
    play_winrate: "37.63",
    wins_on_draw: "253",
    matches_on_draw: "938",
    draw_winrate: "26.97",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/ruby",
    total_matches: "1683",
    wins: "683",
    overall_winrate: "40.58",
    wins_on_play: "357",
    matches_on_play: "812",
    play_winrate: "43.97",
    wins_on_draw: "326",
    matches_on_draw: "871",
    draw_winrate: "37.43",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/sapphire",
    total_matches: "1581",
    wins: "664",
    overall_winrate: "42.00",
    wins_on_play: "360",
    matches_on_play: "744",
    play_winrate: "48.39",
    wins_on_draw: "304",
    matches_on_draw: "837",
    draw_winrate: "36.32",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/steel",
    total_matches: "1251",
    wins: "570",
    overall_winrate: "45.56",
    wins_on_play: "317",
    matches_on_play: "640",
    play_winrate: "49.53",
    wins_on_draw: "253",
    matches_on_draw: "611",
    draw_winrate: "41.41",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/emerald",
    total_matches: "1036",
    wins: "464",
    overall_winrate: "44.79",
    wins_on_play: "262",
    matches_on_play: "496",
    play_winrate: "52.82",
    wins_on_draw: "202",
    matches_on_draw: "540",
    draw_winrate: "37.41",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "sapphire/steel",
    total_matches: "885",
    wins: "450",
    overall_winrate: "50.85",
    wins_on_play: "227",
    matches_on_play: "422",
    play_winrate: "53.79",
    wins_on_draw: "223",
    matches_on_draw: "463",
    draw_winrate: "48.16",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "steel/emerald",
    total_matches: "798",
    wins: "270",
    overall_winrate: "33.83",
    wins_on_play: "153",
    matches_on_play: "394",
    play_winrate: "38.83",
    wins_on_draw: "117",
    matches_on_draw: "404",
    draw_winrate: "28.96",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/sapphire",
    total_matches: "558",
    wins: "251",
    overall_winrate: "44.98",
    wins_on_play: "136",
    matches_on_play: "250",
    play_winrate: "54.40",
    wins_on_draw: "115",
    matches_on_draw: "308",
    draw_winrate: "37.34",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "sapphire/emerald",
    total_matches: "419",
    wins: "215",
    overall_winrate: "51.31",
    wins_on_play: "120",
    matches_on_play: "207",
    play_winrate: "57.97",
    wins_on_draw: "95",
    matches_on_draw: "212",
    draw_winrate: "44.81",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/ruby",
    total_matches: "287",
    wins: "287",
    overall_winrate: "100.00",
    wins_on_play: "220",
    matches_on_play: "220",
    play_winrate: "100.00",
    wins_on_draw: "204",
    matches_on_draw: "204",
    draw_winrate: "100.00",
    mirror_matches: "287",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/steel",
    total_matches: "206",
    wins: "102",
    overall_winrate: "49.51",
    wins_on_play: "53",
    matches_on_play: "98",
    play_winrate: "54.08",
    wins_on_draw: "49",
    matches_on_draw: "108",
    draw_winrate: "45.37",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/emerald",
    total_matches: "203",
    wins: "87",
    overall_winrate: "42.86",
    wins_on_play: "46",
    matches_on_play: "89",
    play_winrate: "51.69",
    wins_on_draw: "41",
    matches_on_draw: "114",
    draw_winrate: "35.96",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/amethyst",
    total_matches: "189",
    wins: "98",
    overall_winrate: "51.85",
    wins_on_play: "55",
    matches_on_play: "95",
    play_winrate: "57.89",
    wins_on_draw: "43",
    matches_on_draw: "94",
    draw_winrate: "45.74",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/emerald",
    total_matches: "97",
    wins: "62",
    overall_winrate: "63.92",
    wins_on_play: "28",
    matches_on_play: "40",
    play_winrate: "70.00",
    wins_on_draw: "34",
    matches_on_draw: "57",
    draw_winrate: "59.65",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/sapphire",
    total_matches: "80",
    wins: "52",
    overall_winrate: "65.00",
    wins_on_play: "23",
    matches_on_play: "33",
    play_winrate: "69.70",
    wins_on_draw: "29",
    matches_on_draw: "47",
    draw_winrate: "61.70",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/steel",
    total_matches: "600",
    wins: "154",
    overall_winrate: "25.67",
    wins_on_play: "101",
    matches_on_play: "326",
    play_winrate: "30.98",
    wins_on_draw: "53",
    matches_on_draw: "274",
    draw_winrate: "19.34",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/ruby",
    total_matches: "499",
    wins: "191",
    overall_winrate: "38.28",
    wins_on_play: "116",
    matches_on_play: "256",
    play_winrate: "45.31",
    wins_on_draw: "75",
    matches_on_draw: "243",
    draw_winrate: "30.86",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/sapphire",
    total_matches: "498",
    wins: "225",
    overall_winrate: "45.18",
    wins_on_play: "150",
    matches_on_play: "261",
    play_winrate: "57.47",
    wins_on_draw: "75",
    matches_on_draw: "237",
    draw_winrate: "31.65",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/steel",
    total_matches: "400",
    wins: "130",
    overall_winrate: "32.50",
    wins_on_play: "75",
    matches_on_play: "194",
    play_winrate: "38.66",
    wins_on_draw: "55",
    matches_on_draw: "206",
    draw_winrate: "26.70",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/emerald",
    total_matches: "364",
    wins: "129",
    overall_winrate: "35.44",
    wins_on_play: "82",
    matches_on_play: "173",
    play_winrate: "47.40",
    wins_on_draw: "47",
    matches_on_draw: "191",
    draw_winrate: "24.61",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire/steel",
    total_matches: "265",
    wins: "131",
    overall_winrate: "49.43",
    wins_on_play: "76",
    matches_on_play: "138",
    play_winrate: "55.07",
    wins_on_draw: "55",
    matches_on_draw: "127",
    draw_winrate: "43.31",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "steel/emerald",
    total_matches: "262",
    wins: "93",
    overall_winrate: "35.50",
    wins_on_play: "53",
    matches_on_play: "130",
    play_winrate: "40.77",
    wins_on_draw: "40",
    matches_on_draw: "132",
    draw_winrate: "30.30",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "184",
    wins: "73",
    overall_winrate: "39.67",
    wins_on_play: "39",
    matches_on_play: "88",
    play_winrate: "44.32",
    wins_on_draw: "34",
    matches_on_draw: "96",
    draw_winrate: "35.42",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire/emerald",
    total_matches: "111",
    wins: "63",
    overall_winrate: "56.76",
    wins_on_play: "37",
    matches_on_play: "57",
    play_winrate: "64.91",
    wins_on_draw: "26",
    matches_on_draw: "54",
    draw_winrate: "48.15",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/ruby",
    total_matches: "80",
    wins: "28",
    overall_winrate: "35.00",
    wins_on_play: "18",
    matches_on_play: "47",
    play_winrate: "38.30",
    wins_on_draw: "10",
    matches_on_draw: "33",
    draw_winrate: "30.30",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/amethyst",
    total_matches: "57",
    wins: "25",
    overall_winrate: "43.86",
    wins_on_play: "14",
    matches_on_play: "27",
    play_winrate: "51.85",
    wins_on_draw: "11",
    matches_on_draw: "30",
    draw_winrate: "36.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/steel",
    total_matches: "53",
    wins: "19",
    overall_winrate: "35.85",
    wins_on_play: "15",
    matches_on_play: "30",
    play_winrate: "50.00",
    wins_on_draw: "4",
    matches_on_draw: "23",
    draw_winrate: "17.39",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/sapphire",
    total_matches: "45",
    wins: "45",
    overall_winrate: "100.00",
    wins_on_play: "38",
    matches_on_play: "38",
    play_winrate: "100.00",
    wins_on_draw: "37",
    matches_on_draw: "37",
    draw_winrate: "100.00",
    mirror_matches: "45",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/emerald",
    total_matches: "41",
    wins: "15",
    overall_winrate: "36.59",
    wins_on_play: "6",
    matches_on_play: "18",
    play_winrate: "33.33",
    wins_on_draw: "9",
    matches_on_draw: "23",
    draw_winrate: "39.13",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/emerald",
    total_matches: "26",
    wins: "19",
    overall_winrate: "73.08",
    wins_on_play: "13",
    matches_on_play: "16",
    play_winrate: "81.25",
    wins_on_draw: "6",
    matches_on_draw: "10",
    draw_winrate: "60.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/sapphire",
    total_matches: "14991",
    wins: "6488",
    overall_winrate: "43.28",
    wins_on_play: "3856",
    matches_on_play: "7555",
    play_winrate: "51.04",
    wins_on_draw: "2632",
    matches_on_draw: "7436",
    draw_winrate: "35.40",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/ruby",
    total_matches: "13523",
    wins: "7408",
    overall_winrate: "54.78",
    wins_on_play: "4333",
    matches_on_play: "6828",
    play_winrate: "63.46",
    wins_on_draw: "3075",
    matches_on_draw: "6695",
    draw_winrate: "45.93",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/steel",
    total_matches: "10190",
    wins: "5527",
    overall_winrate: "54.24",
    wins_on_play: "3088",
    matches_on_play: "5101",
    play_winrate: "60.54",
    wins_on_draw: "2439",
    matches_on_draw: "5089",
    draw_winrate: "47.93",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/steel",
    total_matches: "9506",
    wins: "9506",
    overall_winrate: "100.00",
    wins_on_play: "5910",
    matches_on_play: "5910",
    play_winrate: "100.00",
    wins_on_draw: "4615",
    matches_on_draw: "4615",
    draw_winrate: "100.00",
    mirror_matches: "9506",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/emerald",
    total_matches: "9505",
    wins: "5806",
    overall_winrate: "61.08",
    wins_on_play: "3266",
    matches_on_play: "4788",
    play_winrate: "68.21",
    wins_on_draw: "2540",
    matches_on_draw: "4717",
    draw_winrate: "53.85",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "steel/emerald",
    total_matches: "7140",
    wins: "3818",
    overall_winrate: "53.47",
    wins_on_play: "2067",
    matches_on_play: "3490",
    play_winrate: "59.23",
    wins_on_draw: "1751",
    matches_on_draw: "3650",
    draw_winrate: "47.97",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire/steel",
    total_matches: "6872",
    wins: "3904",
    overall_winrate: "56.81",
    wins_on_play: "2146",
    matches_on_play: "3402",
    play_winrate: "63.08",
    wins_on_draw: "1758",
    matches_on_draw: "3470",
    draw_winrate: "50.66",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/sapphire",
    total_matches: "5429",
    wins: "3049",
    overall_winrate: "56.16",
    wins_on_play: "1677",
    matches_on_play: "2672",
    play_winrate: "62.76",
    wins_on_draw: "1372",
    matches_on_draw: "2757",
    draw_winrate: "49.76",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire/emerald",
    total_matches: "2794",
    wins: "2016",
    overall_winrate: "72.15",
    wins_on_play: "1071",
    matches_on_play: "1388",
    play_winrate: "77.16",
    wins_on_draw: "945",
    matches_on_draw: "1406",
    draw_winrate: "67.21",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/ruby",
    total_matches: "1815",
    wins: "1232",
    overall_winrate: "67.88",
    wins_on_play: "685",
    matches_on_play: "938",
    play_winrate: "73.03",
    wins_on_draw: "547",
    matches_on_draw: "877",
    draw_winrate: "62.37",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/emerald",
    total_matches: "1381",
    wins: "945",
    overall_winrate: "68.43",
    wins_on_play: "531",
    matches_on_play: "710",
    play_winrate: "74.79",
    wins_on_draw: "414",
    matches_on_draw: "671",
    draw_winrate: "61.70",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/amethyst",
    total_matches: "1297",
    wins: "975",
    overall_winrate: "75.17",
    wins_on_play: "507",
    matches_on_play: "632",
    play_winrate: "80.22",
    wins_on_draw: "468",
    matches_on_draw: "665",
    draw_winrate: "70.38",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/steel",
    total_matches: "1022",
    wins: "634",
    overall_winrate: "62.04",
    wins_on_play: "354",
    matches_on_play: "515",
    play_winrate: "68.74",
    wins_on_draw: "280",
    matches_on_draw: "507",
    draw_winrate: "55.23",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/sapphire",
    total_matches: "600",
    wins: "446",
    overall_winrate: "74.33",
    wins_on_play: "221",
    matches_on_play: "274",
    play_winrate: "80.66",
    wins_on_draw: "225",
    matches_on_draw: "326",
    draw_winrate: "69.02",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/emerald",
    total_matches: "521",
    wins: "390",
    overall_winrate: "74.86",
    wins_on_play: "209",
    matches_on_play: "265",
    play_winrate: "78.87",
    wins_on_draw: "181",
    matches_on_draw: "256",
    draw_winrate: "70.70",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst",
    total_matches: "4",
    wins: "3",
    overall_winrate: "75.00",
    wins_on_play: "2",
    matches_on_play: "3",
    play_winrate: "66.67",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber",
    total_matches: "3",
    wins: "1",
    overall_winrate: "33.33",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "2",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/steel",
    total_matches: "9505",
    wins: "3699",
    overall_winrate: "38.92",
    wins_on_play: "2177",
    matches_on_play: "4717",
    play_winrate: "46.15",
    wins_on_draw: "1522",
    matches_on_draw: "4788",
    draw_winrate: "31.79",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/sapphire",
    total_matches: "8330",
    wins: "5047",
    overall_winrate: "60.59",
    wins_on_play: "2876",
    matches_on_play: "4222",
    play_winrate: "68.12",
    wins_on_draw: "2171",
    matches_on_draw: "4108",
    draw_winrate: "52.85",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/ruby",
    total_matches: "8197",
    wins: "5029",
    overall_winrate: "61.35",
    wins_on_play: "2843",
    matches_on_play: "4157",
    play_winrate: "68.39",
    wins_on_draw: "2186",
    matches_on_draw: "4040",
    draw_winrate: "54.11",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/steel",
    total_matches: "6048",
    wins: "2402",
    overall_winrate: "39.72",
    wins_on_play: "1471",
    matches_on_play: "3091",
    play_winrate: "47.59",
    wins_on_draw: "931",
    matches_on_draw: "2957",
    draw_winrate: "31.48",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "steel/emerald",
    total_matches: "4003",
    wins: "1791",
    overall_winrate: "44.74",
    wins_on_play: "999",
    matches_on_play: "1956",
    play_winrate: "51.07",
    wins_on_draw: "792",
    matches_on_draw: "2047",
    draw_winrate: "38.69",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire/steel",
    total_matches: "3870",
    wins: "1705",
    overall_winrate: "44.06",
    wins_on_play: "996",
    matches_on_play: "1943",
    play_winrate: "51.26",
    wins_on_draw: "709",
    matches_on_draw: "1927",
    draw_winrate: "36.79",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/emerald",
    total_matches: "3631",
    wins: "3631",
    overall_winrate: "100.00",
    wins_on_play: "2375",
    matches_on_play: "2375",
    play_winrate: "100.00",
    wins_on_draw: "1891",
    matches_on_draw: "1891",
    draw_winrate: "100.00",
    mirror_matches: "3631",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/sapphire",
    total_matches: "3241",
    wins: "1708",
    overall_winrate: "52.70",
    wins_on_play: "970",
    matches_on_play: "1584",
    play_winrate: "61.24",
    wins_on_draw: "738",
    matches_on_draw: "1657",
    draw_winrate: "44.54",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire/emerald",
    total_matches: "1565",
    wins: "1072",
    overall_winrate: "68.50",
    wins_on_play: "595",
    matches_on_play: "797",
    play_winrate: "74.65",
    wins_on_draw: "477",
    matches_on_draw: "768",
    draw_winrate: "62.11",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/ruby",
    total_matches: "1036",
    wins: "572",
    overall_winrate: "55.21",
    wins_on_play: "338",
    matches_on_play: "540",
    play_winrate: "62.59",
    wins_on_draw: "234",
    matches_on_draw: "496",
    draw_winrate: "47.18",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/emerald",
    total_matches: "824",
    wins: "481",
    overall_winrate: "58.37",
    wins_on_play: "265",
    matches_on_play: "381",
    play_winrate: "69.55",
    wins_on_draw: "216",
    matches_on_draw: "443",
    draw_winrate: "48.76",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/amethyst",
    total_matches: "728",
    wins: "424",
    overall_winrate: "58.24",
    wins_on_play: "243",
    matches_on_play: "356",
    play_winrate: "68.26",
    wins_on_draw: "181",
    matches_on_draw: "372",
    draw_winrate: "48.66",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/steel",
    total_matches: "621",
    wins: "331",
    overall_winrate: "53.30",
    wins_on_play: "186",
    matches_on_play: "328",
    play_winrate: "56.71",
    wins_on_draw: "145",
    matches_on_draw: "293",
    draw_winrate: "49.49",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/sapphire",
    total_matches: "364",
    wins: "235",
    overall_winrate: "64.56",
    wins_on_play: "144",
    matches_on_play: "191",
    play_winrate: "75.39",
    wins_on_draw: "91",
    matches_on_draw: "173",
    draw_winrate: "52.60",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/emerald",
    total_matches: "340",
    wins: "234",
    overall_winrate: "68.82",
    wins_on_play: "119",
    matches_on_play: "164",
    play_winrate: "72.56",
    wins_on_draw: "115",
    matches_on_draw: "176",
    draw_winrate: "65.34",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber",
    total_matches: "4",
    wins: "3",
    overall_winrate: "75.00",
    wins_on_play: "2",
    matches_on_play: "2",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "2",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "emerald",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/steel",
    total_matches: "13523",
    wins: "6115",
    overall_winrate: "45.22",
    wins_on_play: "3620",
    matches_on_play: "6695",
    play_winrate: "54.07",
    wins_on_draw: "2495",
    matches_on_draw: "6828",
    draw_winrate: "36.54",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/sapphire",
    total_matches: "11614",
    wins: "6754",
    overall_winrate: "58.15",
    wins_on_play: "3801",
    matches_on_play: "5841",
    play_winrate: "65.07",
    wins_on_draw: "2953",
    matches_on_draw: "5773",
    draw_winrate: "51.15",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/steel",
    total_matches: "8598",
    wins: "4034",
    overall_winrate: "46.92",
    wins_on_play: "2353",
    matches_on_play: "4366",
    play_winrate: "53.89",
    wins_on_draw: "1681",
    matches_on_draw: "4232",
    draw_winrate: "39.72",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/emerald",
    total_matches: "8197",
    wins: "3168",
    overall_winrate: "38.65",
    wins_on_play: "1854",
    matches_on_play: "4040",
    play_winrate: "45.89",
    wins_on_draw: "1314",
    matches_on_draw: "4157",
    draw_winrate: "31.61",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/ruby",
    total_matches: "6843",
    wins: "6843",
    overall_winrate: "100.00",
    wins_on_play: "4336",
    matches_on_play: "4336",
    play_winrate: "100.00",
    wins_on_draw: "3441",
    matches_on_draw: "3441",
    draw_winrate: "100.00",
    mirror_matches: "6843",
  },
  {
    deck: "amethyst/ruby",
    versus: "steel/emerald",
    total_matches: "5851",
    wins: "2937",
    overall_winrate: "50.20",
    wins_on_play: "1569",
    matches_on_play: "2882",
    play_winrate: "54.44",
    wins_on_draw: "1368",
    matches_on_draw: "2969",
    draw_winrate: "46.08",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire/steel",
    total_matches: "5685",
    wins: "3141",
    overall_winrate: "55.25",
    wins_on_play: "1838",
    matches_on_play: "2934",
    play_winrate: "62.64",
    wins_on_draw: "1303",
    matches_on_draw: "2751",
    draw_winrate: "47.36",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/sapphire",
    total_matches: "4422",
    wins: "2200",
    overall_winrate: "49.75",
    wins_on_play: "1293",
    matches_on_play: "2258",
    play_winrate: "57.26",
    wins_on_draw: "907",
    matches_on_draw: "2164",
    draw_winrate: "41.91",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire/emerald",
    total_matches: "2277",
    wins: "1115",
    overall_winrate: "48.97",
    wins_on_play: "644",
    matches_on_play: "1163",
    play_winrate: "55.37",
    wins_on_draw: "471",
    matches_on_draw: "1114",
    draw_winrate: "42.28",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/ruby",
    total_matches: "1683",
    wins: "1000",
    overall_winrate: "59.42",
    wins_on_play: "545",
    matches_on_play: "871",
    play_winrate: "62.57",
    wins_on_draw: "455",
    matches_on_draw: "812",
    draw_winrate: "56.03",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/emerald",
    total_matches: "1241",
    wins: "659",
    overall_winrate: "53.10",
    wins_on_play: "378",
    matches_on_play: "622",
    play_winrate: "60.77",
    wins_on_draw: "281",
    matches_on_draw: "619",
    draw_winrate: "45.40",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/amethyst",
    total_matches: "1173",
    wins: "542",
    overall_winrate: "46.21",
    wins_on_play: "319",
    matches_on_play: "589",
    play_winrate: "54.16",
    wins_on_draw: "223",
    matches_on_draw: "584",
    draw_winrate: "38.18",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/steel",
    total_matches: "874",
    wins: "589",
    overall_winrate: "67.39",
    wins_on_play: "325",
    matches_on_play: "443",
    play_winrate: "73.36",
    wins_on_draw: "264",
    matches_on_draw: "431",
    draw_winrate: "61.25",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/emerald",
    total_matches: "507",
    wins: "306",
    overall_winrate: "60.36",
    wins_on_play: "179",
    matches_on_play: "263",
    play_winrate: "68.06",
    wins_on_draw: "127",
    matches_on_draw: "244",
    draw_winrate: "52.05",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/sapphire",
    total_matches: "499",
    wins: "308",
    overall_winrate: "61.72",
    wins_on_play: "168",
    matches_on_play: "243",
    play_winrate: "69.14",
    wins_on_draw: "140",
    matches_on_draw: "256",
    draw_winrate: "54.69",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire",
    total_matches: "3",
    wins: "3",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "2",
    matches_on_draw: "2",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "steel",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/steel",
    total_matches: "5429",
    wins: "2380",
    overall_winrate: "43.84",
    wins_on_play: "1385",
    matches_on_play: "2757",
    play_winrate: "50.24",
    wins_on_draw: "995",
    matches_on_draw: "2672",
    draw_winrate: "37.24",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/sapphire",
    total_matches: "4768",
    wins: "2226",
    overall_winrate: "46.69",
    wins_on_play: "1259",
    matches_on_play: "2384",
    play_winrate: "52.81",
    wins_on_draw: "967",
    matches_on_draw: "2384",
    draw_winrate: "40.56",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/ruby",
    total_matches: "4422",
    wins: "2222",
    overall_winrate: "50.25",
    wins_on_play: "1257",
    matches_on_play: "2164",
    play_winrate: "58.09",
    wins_on_draw: "965",
    matches_on_draw: "2258",
    draw_winrate: "42.74",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/steel",
    total_matches: "3388",
    wins: "1752",
    overall_winrate: "51.71",
    wins_on_play: "993",
    matches_on_play: "1649",
    play_winrate: "60.22",
    wins_on_draw: "759",
    matches_on_draw: "1739",
    draw_winrate: "43.65",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/emerald",
    total_matches: "3241",
    wins: "1533",
    overall_winrate: "47.30",
    wins_on_play: "919",
    matches_on_play: "1657",
    play_winrate: "55.46",
    wins_on_draw: "614",
    matches_on_draw: "1584",
    draw_winrate: "38.76",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "steel/emerald",
    total_matches: "2298",
    wins: "1024",
    overall_winrate: "44.56",
    wins_on_play: "569",
    matches_on_play: "1138",
    play_winrate: "50.00",
    wins_on_draw: "455",
    matches_on_draw: "1160",
    draw_winrate: "39.22",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "sapphire/steel",
    total_matches: "2172",
    wins: "1200",
    overall_winrate: "55.25",
    wins_on_play: "695",
    matches_on_play: "1085",
    play_winrate: "64.06",
    wins_on_draw: "505",
    matches_on_draw: "1087",
    draw_winrate: "46.46",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "1162",
    wins: "1162",
    overall_winrate: "100.00",
    wins_on_play: "793",
    matches_on_play: "793",
    play_winrate: "100.00",
    wins_on_draw: "660",
    matches_on_draw: "660",
    draw_winrate: "100.00",
    mirror_matches: "1162",
  },
  {
    deck: "amethyst/sapphire",
    versus: "sapphire/emerald",
    total_matches: "982",
    wins: "531",
    overall_winrate: "54.07",
    wins_on_play: "288",
    matches_on_play: "494",
    play_winrate: "58.30",
    wins_on_draw: "243",
    matches_on_draw: "488",
    draw_winrate: "49.80",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/ruby",
    total_matches: "558",
    wins: "307",
    overall_winrate: "55.02",
    wins_on_play: "193",
    matches_on_play: "308",
    play_winrate: "62.66",
    wins_on_draw: "114",
    matches_on_draw: "250",
    draw_winrate: "45.60",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/emerald",
    total_matches: "498",
    wins: "244",
    overall_winrate: "49.00",
    wins_on_play: "150",
    matches_on_play: "258",
    play_winrate: "58.14",
    wins_on_draw: "94",
    matches_on_draw: "240",
    draw_winrate: "39.17",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/amethyst",
    total_matches: "424",
    wins: "210",
    overall_winrate: "49.53",
    wins_on_play: "129",
    matches_on_play: "212",
    play_winrate: "60.85",
    wins_on_draw: "81",
    matches_on_draw: "212",
    draw_winrate: "38.21",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/steel",
    total_matches: "336",
    wins: "217",
    overall_winrate: "64.58",
    wins_on_play: "114",
    matches_on_play: "168",
    play_winrate: "67.86",
    wins_on_draw: "103",
    matches_on_draw: "168",
    draw_winrate: "61.31",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/emerald",
    total_matches: "190",
    wins: "120",
    overall_winrate: "63.16",
    wins_on_play: "63",
    matches_on_play: "93",
    play_winrate: "67.74",
    wins_on_draw: "57",
    matches_on_draw: "97",
    draw_winrate: "58.76",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/sapphire",
    total_matches: "184",
    wins: "111",
    overall_winrate: "60.33",
    wins_on_play: "62",
    matches_on_play: "96",
    play_winrate: "64.58",
    wins_on_draw: "49",
    matches_on_draw: "88",
    draw_winrate: "55.68",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/steel",
    total_matches: "10190",
    wins: "4663",
    overall_winrate: "45.76",
    wins_on_play: "2650",
    matches_on_play: "5089",
    play_winrate: "52.07",
    wins_on_draw: "2013",
    matches_on_draw: "5101",
    draw_winrate: "39.46",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/sapphire",
    total_matches: "9225",
    wins: "4546",
    overall_winrate: "49.28",
    wins_on_play: "2590",
    matches_on_play: "4572",
    play_winrate: "56.65",
    wins_on_draw: "1956",
    matches_on_draw: "4653",
    draw_winrate: "42.04",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/ruby",
    total_matches: "8598",
    wins: "4564",
    overall_winrate: "53.08",
    wins_on_play: "2551",
    matches_on_play: "4232",
    play_winrate: "60.28",
    wins_on_draw: "2013",
    matches_on_draw: "4366",
    draw_winrate: "46.11",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/emerald",
    total_matches: "6048",
    wins: "3646",
    overall_winrate: "60.28",
    wins_on_play: "2026",
    matches_on_play: "2957",
    play_winrate: "68.52",
    wins_on_draw: "1620",
    matches_on_draw: "3091",
    draw_winrate: "52.41",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "steel/emerald",
    total_matches: "4382",
    wins: "2179",
    overall_winrate: "49.73",
    wins_on_play: "1187",
    matches_on_play: "2172",
    play_winrate: "54.65",
    wins_on_draw: "992",
    matches_on_draw: "2210",
    draw_winrate: "44.89",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire/steel",
    total_matches: "4279",
    wins: "2123",
    overall_winrate: "49.61",
    wins_on_play: "1223",
    matches_on_play: "2153",
    play_winrate: "56.80",
    wins_on_draw: "900",
    matches_on_draw: "2126",
    draw_winrate: "42.33",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/steel",
    total_matches: "4020",
    wins: "4020",
    overall_winrate: "100.00",
    wins_on_play: "2537",
    matches_on_play: "2537",
    play_winrate: "100.00",
    wins_on_draw: "2175",
    matches_on_draw: "2175",
    draw_winrate: "100.00",
    mirror_matches: "4020",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/sapphire",
    total_matches: "3388",
    wins: "1636",
    overall_winrate: "48.29",
    wins_on_play: "980",
    matches_on_play: "1739",
    play_winrate: "56.35",
    wins_on_draw: "656",
    matches_on_draw: "1649",
    draw_winrate: "39.78",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire/emerald",
    total_matches: "1716",
    wins: "1095",
    overall_winrate: "63.81",
    wins_on_play: "602",
    matches_on_play: "859",
    play_winrate: "70.08",
    wins_on_draw: "493",
    matches_on_draw: "857",
    draw_winrate: "57.53",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/ruby",
    total_matches: "1251",
    wins: "681",
    overall_winrate: "54.44",
    wins_on_play: "358",
    matches_on_play: "611",
    play_winrate: "58.59",
    wins_on_draw: "323",
    matches_on_draw: "640",
    draw_winrate: "50.47",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/emerald",
    total_matches: "939",
    wins: "583",
    overall_winrate: "62.09",
    wins_on_play: "300",
    matches_on_play: "457",
    play_winrate: "65.65",
    wins_on_draw: "283",
    matches_on_draw: "482",
    draw_winrate: "58.71",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/amethyst",
    total_matches: "845",
    wins: "538",
    overall_winrate: "63.67",
    wins_on_play: "301",
    matches_on_play: "418",
    play_winrate: "72.01",
    wins_on_draw: "237",
    matches_on_draw: "427",
    draw_winrate: "55.50",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/steel",
    total_matches: "675",
    wins: "441",
    overall_winrate: "65.33",
    wins_on_play: "237",
    matches_on_play: "328",
    play_winrate: "72.26",
    wins_on_draw: "204",
    matches_on_draw: "347",
    draw_winrate: "58.79",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/sapphire",
    total_matches: "400",
    wins: "270",
    overall_winrate: "67.50",
    wins_on_play: "151",
    matches_on_play: "206",
    play_winrate: "73.30",
    wins_on_draw: "119",
    matches_on_draw: "194",
    draw_winrate: "61.34",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/emerald",
    total_matches: "358",
    wins: "253",
    overall_winrate: "70.67",
    wins_on_play: "136",
    matches_on_play: "185",
    play_winrate: "73.51",
    wins_on_draw: "117",
    matches_on_draw: "173",
    draw_winrate: "67.63",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/steel",
    total_matches: "521",
    wins: "131",
    overall_winrate: "25.14",
    wins_on_play: "75",
    matches_on_play: "256",
    play_winrate: "29.30",
    wins_on_draw: "56",
    matches_on_draw: "265",
    draw_winrate: "21.13",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/ruby",
    total_matches: "507",
    wins: "201",
    overall_winrate: "39.64",
    wins_on_play: "117",
    matches_on_play: "244",
    play_winrate: "47.95",
    wins_on_draw: "84",
    matches_on_draw: "263",
    draw_winrate: "31.94",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/sapphire",
    total_matches: "456",
    wins: "182",
    overall_winrate: "39.91",
    wins_on_play: "95",
    matches_on_play: "231",
    play_winrate: "41.13",
    wins_on_draw: "87",
    matches_on_draw: "225",
    draw_winrate: "38.67",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/steel",
    total_matches: "358",
    wins: "105",
    overall_winrate: "29.33",
    wins_on_play: "56",
    matches_on_play: "173",
    play_winrate: "32.37",
    wins_on_draw: "49",
    matches_on_draw: "185",
    draw_winrate: "26.49",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/emerald",
    total_matches: "340",
    wins: "106",
    overall_winrate: "31.18",
    wins_on_play: "61",
    matches_on_play: "176",
    play_winrate: "34.66",
    wins_on_draw: "45",
    matches_on_draw: "164",
    draw_winrate: "27.44",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "steel/emerald",
    total_matches: "288",
    wins: "99",
    overall_winrate: "34.38",
    wins_on_play: "51",
    matches_on_play: "125",
    play_winrate: "40.80",
    wins_on_draw: "48",
    matches_on_draw: "163",
    draw_winrate: "29.45",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "sapphire/steel",
    total_matches: "269",
    wins: "98",
    overall_winrate: "36.43",
    wins_on_play: "53",
    matches_on_play: "137",
    play_winrate: "38.69",
    wins_on_draw: "45",
    matches_on_draw: "132",
    draw_winrate: "34.09",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/sapphire",
    total_matches: "190",
    wins: "70",
    overall_winrate: "36.84",
    wins_on_play: "40",
    matches_on_play: "97",
    play_winrate: "41.24",
    wins_on_draw: "30",
    matches_on_draw: "93",
    draw_winrate: "32.26",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "sapphire/emerald",
    total_matches: "124",
    wins: "76",
    overall_winrate: "61.29",
    wins_on_play: "41",
    matches_on_play: "68",
    play_winrate: "60.29",
    wins_on_draw: "35",
    matches_on_draw: "56",
    draw_winrate: "62.50",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/ruby",
    total_matches: "97",
    wins: "35",
    overall_winrate: "36.08",
    wins_on_play: "23",
    matches_on_play: "57",
    play_winrate: "40.35",
    wins_on_draw: "12",
    matches_on_draw: "40",
    draw_winrate: "30.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/steel",
    total_matches: "75",
    wins: "28",
    overall_winrate: "37.33",
    wins_on_play: "15",
    matches_on_play: "41",
    play_winrate: "36.59",
    wins_on_draw: "13",
    matches_on_draw: "34",
    draw_winrate: "38.24",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/emerald",
    total_matches: "72",
    wins: "32",
    overall_winrate: "44.44",
    wins_on_play: "18",
    matches_on_play: "36",
    play_winrate: "50.00",
    wins_on_draw: "14",
    matches_on_draw: "36",
    draw_winrate: "38.89",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/amethyst",
    total_matches: "65",
    wins: "28",
    overall_winrate: "43.08",
    wins_on_play: "19",
    matches_on_play: "38",
    play_winrate: "50.00",
    wins_on_draw: "9",
    matches_on_draw: "27",
    draw_winrate: "33.33",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/emerald",
    total_matches: "56",
    wins: "56",
    overall_winrate: "100.00",
    wins_on_play: "48",
    matches_on_play: "48",
    play_winrate: "100.00",
    wins_on_draw: "49",
    matches_on_draw: "49",
    draw_winrate: "100.00",
    mirror_matches: "56",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/sapphire",
    total_matches: "26",
    wins: "7",
    overall_winrate: "26.92",
    wins_on_play: "4",
    matches_on_play: "10",
    play_winrate: "40.00",
    wins_on_draw: "3",
    matches_on_draw: "16",
    draw_winrate: "18.75",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/steel",
    total_matches: "2794",
    wins: "778",
    overall_winrate: "27.85",
    wins_on_play: "461",
    matches_on_play: "1406",
    play_winrate: "32.79",
    wins_on_draw: "317",
    matches_on_draw: "1388",
    draw_winrate: "22.84",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/sapphire",
    total_matches: "2301",
    wins: "1102",
    overall_winrate: "47.89",
    wins_on_play: "605",
    matches_on_play: "1179",
    play_winrate: "51.31",
    wins_on_draw: "497",
    matches_on_draw: "1122",
    draw_winrate: "44.30",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/ruby",
    total_matches: "2277",
    wins: "1162",
    overall_winrate: "51.03",
    wins_on_play: "643",
    matches_on_play: "1114",
    play_winrate: "57.72",
    wins_on_draw: "519",
    matches_on_draw: "1163",
    draw_winrate: "44.63",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/steel",
    total_matches: "1716",
    wins: "621",
    overall_winrate: "36.19",
    wins_on_play: "364",
    matches_on_play: "857",
    play_winrate: "42.47",
    wins_on_draw: "257",
    matches_on_draw: "859",
    draw_winrate: "29.92",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/emerald",
    total_matches: "1565",
    wins: "493",
    overall_winrate: "31.50",
    wins_on_play: "291",
    matches_on_play: "768",
    play_winrate: "37.89",
    wins_on_draw: "202",
    matches_on_draw: "797",
    draw_winrate: "25.35",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "sapphire/steel",
    total_matches: "1266",
    wins: "502",
    overall_winrate: "39.65",
    wins_on_play: "293",
    matches_on_play: "659",
    play_winrate: "44.46",
    wins_on_draw: "209",
    matches_on_draw: "607",
    draw_winrate: "34.43",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "steel/emerald",
    total_matches: "1184",
    wins: "353",
    overall_winrate: "29.81",
    wins_on_play: "213",
    matches_on_play: "587",
    play_winrate: "36.29",
    wins_on_draw: "140",
    matches_on_draw: "597",
    draw_winrate: "23.45",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/sapphire",
    total_matches: "982",
    wins: "451",
    overall_winrate: "45.93",
    wins_on_play: "245",
    matches_on_play: "488",
    play_winrate: "50.20",
    wins_on_draw: "206",
    matches_on_draw: "494",
    draw_winrate: "41.70",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "sapphire/emerald",
    total_matches: "487",
    wins: "487",
    overall_winrate: "100.00",
    wins_on_play: "370",
    matches_on_play: "370",
    play_winrate: "100.00",
    wins_on_draw: "304",
    matches_on_draw: "304",
    draw_winrate: "100.00",
    mirror_matches: "487",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/ruby",
    total_matches: "419",
    wins: "204",
    overall_winrate: "48.69",
    wins_on_play: "117",
    matches_on_play: "212",
    play_winrate: "55.19",
    wins_on_draw: "87",
    matches_on_draw: "207",
    draw_winrate: "42.03",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/emerald",
    total_matches: "276",
    wins: "89",
    overall_winrate: "32.25",
    wins_on_play: "52",
    matches_on_play: "133",
    play_winrate: "39.10",
    wins_on_draw: "37",
    matches_on_draw: "143",
    draw_winrate: "25.87",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/steel",
    total_matches: "235",
    wins: "84",
    overall_winrate: "35.74",
    wins_on_play: "53",
    matches_on_play: "113",
    play_winrate: "46.90",
    wins_on_draw: "31",
    matches_on_draw: "122",
    draw_winrate: "25.41",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/amethyst",
    total_matches: "234",
    wins: "102",
    overall_winrate: "43.59",
    wins_on_play: "61",
    matches_on_play: "120",
    play_winrate: "50.83",
    wins_on_draw: "41",
    matches_on_draw: "114",
    draw_winrate: "35.96",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/emerald",
    total_matches: "124",
    wins: "48",
    overall_winrate: "38.71",
    wins_on_play: "21",
    matches_on_play: "56",
    play_winrate: "37.50",
    wins_on_draw: "27",
    matches_on_draw: "68",
    draw_winrate: "39.71",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/sapphire",
    total_matches: "111",
    wins: "48",
    overall_winrate: "43.24",
    wins_on_play: "28",
    matches_on_play: "54",
    play_winrate: "51.85",
    wins_on_draw: "20",
    matches_on_draw: "57",
    draw_winrate: "35.09",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/steel",
    total_matches: "7140",
    wins: "3322",
    overall_winrate: "46.53",
    wins_on_play: "1899",
    matches_on_play: "3650",
    play_winrate: "52.03",
    wins_on_draw: "1423",
    matches_on_draw: "3490",
    draw_winrate: "40.77",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/sapphire",
    total_matches: "6415",
    wins: "2706",
    overall_winrate: "42.18",
    wins_on_play: "1464",
    matches_on_play: "3238",
    play_winrate: "45.21",
    wins_on_draw: "1242",
    matches_on_draw: "3177",
    draw_winrate: "39.09",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/ruby",
    total_matches: "5851",
    wins: "2914",
    overall_winrate: "49.80",
    wins_on_play: "1601",
    matches_on_play: "2969",
    play_winrate: "53.92",
    wins_on_draw: "1313",
    matches_on_draw: "2882",
    draw_winrate: "45.56",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/steel",
    total_matches: "4382",
    wins: "2203",
    overall_winrate: "50.27",
    wins_on_play: "1218",
    matches_on_play: "2210",
    play_winrate: "55.11",
    wins_on_draw: "985",
    matches_on_draw: "2172",
    draw_winrate: "45.35",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/emerald",
    total_matches: "4003",
    wins: "2212",
    overall_winrate: "55.26",
    wins_on_play: "1255",
    matches_on_play: "2047",
    play_winrate: "61.31",
    wins_on_draw: "957",
    matches_on_draw: "1956",
    draw_winrate: "48.93",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "sapphire/steel",
    total_matches: "3054",
    wins: "1416",
    overall_winrate: "46.37",
    wins_on_play: "789",
    matches_on_play: "1584",
    play_winrate: "49.81",
    wins_on_draw: "627",
    matches_on_draw: "1470",
    draw_winrate: "42.65",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/sapphire",
    total_matches: "2298",
    wins: "1274",
    overall_winrate: "55.44",
    wins_on_play: "705",
    matches_on_play: "1160",
    play_winrate: "60.78",
    wins_on_draw: "569",
    matches_on_draw: "1138",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "steel/emerald",
    total_matches: "2007",
    wins: "2007",
    overall_winrate: "100.00",
    wins_on_play: "1311",
    matches_on_play: "1311",
    play_winrate: "100.00",
    wins_on_draw: "1205",
    matches_on_draw: "1205",
    draw_winrate: "100.00",
    mirror_matches: "2007",
  },
  {
    deck: "steel/emerald",
    versus: "sapphire/emerald",
    total_matches: "1184",
    wins: "831",
    overall_winrate: "70.19",
    wins_on_play: "457",
    matches_on_play: "597",
    play_winrate: "76.55",
    wins_on_draw: "374",
    matches_on_draw: "587",
    draw_winrate: "63.71",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/ruby",
    total_matches: "798",
    wins: "528",
    overall_winrate: "66.17",
    wins_on_play: "287",
    matches_on_play: "404",
    play_winrate: "71.04",
    wins_on_draw: "241",
    matches_on_draw: "394",
    draw_winrate: "61.17",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/emerald",
    total_matches: "623",
    wins: "401",
    overall_winrate: "64.37",
    wins_on_play: "232",
    matches_on_play: "326",
    play_winrate: "71.17",
    wins_on_draw: "169",
    matches_on_draw: "297",
    draw_winrate: "56.90",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/amethyst",
    total_matches: "546",
    wins: "387",
    overall_winrate: "70.88",
    wins_on_play: "227",
    matches_on_play: "289",
    play_winrate: "78.55",
    wins_on_draw: "160",
    matches_on_draw: "257",
    draw_winrate: "62.26",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/steel",
    total_matches: "463",
    wins: "293",
    overall_winrate: "63.28",
    wins_on_play: "148",
    matches_on_play: "224",
    play_winrate: "66.07",
    wins_on_draw: "145",
    matches_on_draw: "239",
    draw_winrate: "60.67",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/emerald",
    total_matches: "288",
    wins: "189",
    overall_winrate: "65.63",
    wins_on_play: "115",
    matches_on_play: "163",
    play_winrate: "70.55",
    wins_on_draw: "74",
    matches_on_draw: "125",
    draw_winrate: "59.20",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/sapphire",
    total_matches: "262",
    wins: "169",
    overall_winrate: "64.50",
    wins_on_play: "92",
    matches_on_play: "132",
    play_winrate: "69.70",
    wins_on_draw: "77",
    matches_on_draw: "130",
    draw_winrate: "59.23",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber",
    total_matches: "4",
    wins: "4",
    overall_winrate: "100.00",
    wins_on_play: "3",
    matches_on_play: "3",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/steel",
    total_matches: "14991",
    wins: "8503",
    overall_winrate: "56.72",
    wins_on_play: "4804",
    matches_on_play: "7436",
    play_winrate: "64.60",
    wins_on_draw: "3699",
    matches_on_draw: "7555",
    draw_winrate: "48.96",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/ruby",
    total_matches: "11614",
    wins: "4860",
    overall_winrate: "41.85",
    wins_on_play: "2820",
    matches_on_play: "5773",
    play_winrate: "48.85",
    wins_on_draw: "2040",
    matches_on_draw: "5841",
    draw_winrate: "34.93",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/steel",
    total_matches: "9225",
    wins: "4679",
    overall_winrate: "50.72",
    wins_on_play: "2697",
    matches_on_play: "4653",
    play_winrate: "57.96",
    wins_on_draw: "1982",
    matches_on_draw: "4572",
    draw_winrate: "43.35",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/emerald",
    total_matches: "8330",
    wins: "3283",
    overall_winrate: "39.41",
    wins_on_play: "1937",
    matches_on_play: "4108",
    play_winrate: "47.15",
    wins_on_draw: "1346",
    matches_on_draw: "4222",
    draw_winrate: "31.88",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/sapphire",
    total_matches: "7928",
    wins: "7928",
    overall_winrate: "100.00",
    wins_on_play: "4641",
    matches_on_play: "4641",
    play_winrate: "100.00",
    wins_on_draw: "4160",
    matches_on_draw: "4160",
    draw_winrate: "100.00",
    mirror_matches: "7928",
  },
  {
    deck: "ruby/sapphire",
    versus: "steel/emerald",
    total_matches: "6415",
    wins: "3709",
    overall_winrate: "57.82",
    wins_on_play: "1935",
    matches_on_play: "3177",
    play_winrate: "60.91",
    wins_on_draw: "1774",
    matches_on_draw: "3238",
    draw_winrate: "54.79",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire/steel",
    total_matches: "5947",
    wins: "3618",
    overall_winrate: "60.84",
    wins_on_play: "1954",
    matches_on_play: "2948",
    play_winrate: "66.28",
    wins_on_draw: "1664",
    matches_on_draw: "2999",
    draw_winrate: "55.49",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "4768",
    wins: "2542",
    overall_winrate: "53.31",
    wins_on_play: "1417",
    matches_on_play: "2384",
    play_winrate: "59.44",
    wins_on_draw: "1125",
    matches_on_draw: "2384",
    draw_winrate: "47.19",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire/emerald",
    total_matches: "2301",
    wins: "1199",
    overall_winrate: "52.11",
    wins_on_play: "625",
    matches_on_play: "1122",
    play_winrate: "55.70",
    wins_on_draw: "574",
    matches_on_draw: "1179",
    draw_winrate: "48.69",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/ruby",
    total_matches: "1581",
    wins: "917",
    overall_winrate: "58.00",
    wins_on_play: "533",
    matches_on_play: "837",
    play_winrate: "63.68",
    wins_on_draw: "384",
    matches_on_draw: "744",
    draw_winrate: "51.61",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/emerald",
    total_matches: "1269",
    wins: "607",
    overall_winrate: "47.83",
    wins_on_play: "353",
    matches_on_play: "636",
    play_winrate: "55.50",
    wins_on_draw: "254",
    matches_on_draw: "633",
    draw_winrate: "40.13",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/amethyst",
    total_matches: "1108",
    wins: "421",
    overall_winrate: "38.00",
    wins_on_play: "267",
    matches_on_play: "560",
    play_winrate: "47.68",
    wins_on_draw: "154",
    matches_on_draw: "548",
    draw_winrate: "28.10",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/steel",
    total_matches: "905",
    wins: "645",
    overall_winrate: "71.27",
    wins_on_play: "360",
    matches_on_play: "464",
    play_winrate: "77.59",
    wins_on_draw: "285",
    matches_on_draw: "441",
    draw_winrate: "64.63",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/sapphire",
    total_matches: "498",
    wins: "273",
    overall_winrate: "54.82",
    wins_on_play: "162",
    matches_on_play: "237",
    play_winrate: "68.35",
    wins_on_draw: "111",
    matches_on_draw: "261",
    draw_winrate: "42.53",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/emerald",
    total_matches: "456",
    wins: "274",
    overall_winrate: "60.09",
    wins_on_play: "138",
    matches_on_play: "225",
    play_winrate: "61.33",
    wins_on_draw: "136",
    matches_on_draw: "231",
    draw_winrate: "58.87",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "steel",
    total_matches: "4",
    wins: "4",
    overall_winrate: "100.00",
    wins_on_play: "2",
    matches_on_play: "2",
    play_winrate: "100.00",
    wins_on_draw: "2",
    matches_on_draw: "2",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst",
    total_matches: "3",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "2",
    play_winrate: "0.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/steel",
    total_matches: "1022",
    wins: "388",
    overall_winrate: "37.96",
    wins_on_play: "227",
    matches_on_play: "507",
    play_winrate: "44.77",
    wins_on_draw: "161",
    matches_on_draw: "515",
    draw_winrate: "31.26",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/sapphire",
    total_matches: "905",
    wins: "260",
    overall_winrate: "28.73",
    wins_on_play: "156",
    matches_on_play: "441",
    play_winrate: "35.37",
    wins_on_draw: "104",
    matches_on_draw: "464",
    draw_winrate: "22.41",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/ruby",
    total_matches: "874",
    wins: "285",
    overall_winrate: "32.61",
    wins_on_play: "167",
    matches_on_play: "431",
    play_winrate: "38.75",
    wins_on_draw: "118",
    matches_on_draw: "443",
    draw_winrate: "26.64",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/steel",
    total_matches: "675",
    wins: "234",
    overall_winrate: "34.67",
    wins_on_play: "143",
    matches_on_play: "347",
    play_winrate: "41.21",
    wins_on_draw: "91",
    matches_on_draw: "328",
    draw_winrate: "27.74",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/emerald",
    total_matches: "621",
    wins: "290",
    overall_winrate: "46.70",
    wins_on_play: "148",
    matches_on_play: "293",
    play_winrate: "50.51",
    wins_on_draw: "142",
    matches_on_draw: "328",
    draw_winrate: "43.29",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "steel/emerald",
    total_matches: "463",
    wins: "170",
    overall_winrate: "36.72",
    wins_on_play: "94",
    matches_on_play: "239",
    play_winrate: "39.33",
    wins_on_draw: "76",
    matches_on_draw: "224",
    draw_winrate: "33.93",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "sapphire/steel",
    total_matches: "461",
    wins: "193",
    overall_winrate: "41.87",
    wins_on_play: "101",
    matches_on_play: "228",
    play_winrate: "44.30",
    wins_on_draw: "92",
    matches_on_draw: "233",
    draw_winrate: "39.48",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/sapphire",
    total_matches: "336",
    wins: "119",
    overall_winrate: "35.42",
    wins_on_play: "65",
    matches_on_play: "168",
    play_winrate: "38.69",
    wins_on_draw: "54",
    matches_on_draw: "168",
    draw_winrate: "32.14",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "sapphire/emerald",
    total_matches: "235",
    wins: "151",
    overall_winrate: "64.26",
    wins_on_play: "91",
    matches_on_play: "122",
    play_winrate: "74.59",
    wins_on_draw: "60",
    matches_on_draw: "113",
    draw_winrate: "53.10",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/ruby",
    total_matches: "206",
    wins: "104",
    overall_winrate: "50.49",
    wins_on_play: "59",
    matches_on_play: "108",
    play_winrate: "54.63",
    wins_on_draw: "45",
    matches_on_draw: "98",
    draw_winrate: "45.92",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/steel",
    total_matches: "151",
    wins: "151",
    overall_winrate: "100.00",
    wins_on_play: "120",
    matches_on_play: "120",
    play_winrate: "100.00",
    wins_on_draw: "120",
    matches_on_draw: "120",
    draw_winrate: "100.00",
    mirror_matches: "151",
  },
  {
    deck: "ruby/steel",
    versus: "amber/emerald",
    total_matches: "132",
    wins: "77",
    overall_winrate: "58.33",
    wins_on_play: "39",
    matches_on_play: "66",
    play_winrate: "59.09",
    wins_on_draw: "38",
    matches_on_draw: "66",
    draw_winrate: "57.58",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/amethyst",
    total_matches: "126",
    wins: "81",
    overall_winrate: "64.29",
    wins_on_play: "51",
    matches_on_play: "75",
    play_winrate: "68.00",
    wins_on_draw: "30",
    matches_on_draw: "51",
    draw_winrate: "58.82",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/emerald",
    total_matches: "75",
    wins: "47",
    overall_winrate: "62.67",
    wins_on_play: "21",
    matches_on_play: "34",
    play_winrate: "61.76",
    wins_on_draw: "26",
    matches_on_draw: "41",
    draw_winrate: "63.41",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/sapphire",
    total_matches: "53",
    wins: "34",
    overall_winrate: "64.15",
    wins_on_play: "19",
    matches_on_play: "23",
    play_winrate: "82.61",
    wins_on_draw: "15",
    matches_on_draw: "30",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/steel",
    total_matches: "6872",
    wins: "2968",
    overall_winrate: "43.19",
    wins_on_play: "1712",
    matches_on_play: "3470",
    play_winrate: "49.34",
    wins_on_draw: "1256",
    matches_on_draw: "3402",
    draw_winrate: "36.92",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/sapphire",
    total_matches: "5947",
    wins: "2329",
    overall_winrate: "39.16",
    wins_on_play: "1335",
    matches_on_play: "2999",
    play_winrate: "44.51",
    wins_on_draw: "994",
    matches_on_draw: "2948",
    draw_winrate: "33.72",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/ruby",
    total_matches: "5685",
    wins: "2544",
    overall_winrate: "44.75",
    wins_on_play: "1448",
    matches_on_play: "2751",
    play_winrate: "52.64",
    wins_on_draw: "1096",
    matches_on_draw: "2934",
    draw_winrate: "37.36",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/steel",
    total_matches: "4279",
    wins: "2156",
    overall_winrate: "50.39",
    wins_on_play: "1226",
    matches_on_play: "2126",
    play_winrate: "57.67",
    wins_on_draw: "930",
    matches_on_draw: "2153",
    draw_winrate: "43.20",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/emerald",
    total_matches: "3870",
    wins: "2165",
    overall_winrate: "55.94",
    wins_on_play: "1218",
    matches_on_play: "1927",
    play_winrate: "63.21",
    wins_on_draw: "947",
    matches_on_draw: "1943",
    draw_winrate: "48.74",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "steel/emerald",
    total_matches: "3054",
    wins: "1638",
    overall_winrate: "53.63",
    wins_on_play: "843",
    matches_on_play: "1470",
    play_winrate: "57.35",
    wins_on_draw: "795",
    matches_on_draw: "1584",
    draw_winrate: "50.19",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/sapphire",
    total_matches: "2172",
    wins: "972",
    overall_winrate: "44.75",
    wins_on_play: "582",
    matches_on_play: "1087",
    play_winrate: "53.54",
    wins_on_draw: "390",
    matches_on_draw: "1085",
    draw_winrate: "35.94",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "sapphire/steel",
    total_matches: "1853",
    wins: "1853",
    overall_winrate: "100.00",
    wins_on_play: "1226",
    matches_on_play: "1226",
    play_winrate: "100.00",
    wins_on_draw: "1027",
    matches_on_draw: "1027",
    draw_winrate: "100.00",
    mirror_matches: "1853",
  },
  {
    deck: "sapphire/steel",
    versus: "sapphire/emerald",
    total_matches: "1266",
    wins: "764",
    overall_winrate: "60.35",
    wins_on_play: "398",
    matches_on_play: "607",
    play_winrate: "65.57",
    wins_on_draw: "366",
    matches_on_draw: "659",
    draw_winrate: "55.54",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/ruby",
    total_matches: "885",
    wins: "435",
    overall_winrate: "49.15",
    wins_on_play: "240",
    matches_on_play: "463",
    play_winrate: "51.84",
    wins_on_draw: "195",
    matches_on_draw: "422",
    draw_winrate: "46.21",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/emerald",
    total_matches: "613",
    wins: "341",
    overall_winrate: "55.63",
    wins_on_play: "196",
    matches_on_play: "311",
    play_winrate: "63.02",
    wins_on_draw: "145",
    matches_on_draw: "302",
    draw_winrate: "48.01",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/amethyst",
    total_matches: "591",
    wins: "301",
    overall_winrate: "50.93",
    wins_on_play: "169",
    matches_on_play: "288",
    play_winrate: "58.68",
    wins_on_draw: "132",
    matches_on_draw: "303",
    draw_winrate: "43.56",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/steel",
    total_matches: "461",
    wins: "268",
    overall_winrate: "58.13",
    wins_on_play: "141",
    matches_on_play: "233",
    play_winrate: "60.52",
    wins_on_draw: "127",
    matches_on_draw: "228",
    draw_winrate: "55.70",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/emerald",
    total_matches: "269",
    wins: "171",
    overall_winrate: "63.57",
    wins_on_play: "87",
    matches_on_play: "132",
    play_winrate: "65.91",
    wins_on_draw: "84",
    matches_on_draw: "137",
    draw_winrate: "61.31",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/sapphire",
    total_matches: "265",
    wins: "134",
    overall_winrate: "50.57",
    wins_on_play: "72",
    matches_on_play: "127",
    play_winrate: "56.69",
    wins_on_draw: "62",
    matches_on_draw: "138",
    draw_winrate: "44.93",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber",
    total_matches: "8",
    wins: "6",
    overall_winrate: "75.00",
    wins_on_play: "4",
    matches_on_play: "5",
    play_winrate: "80.00",
    wins_on_draw: "2",
    matches_on_draw: "3",
    draw_winrate: "66.67",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
];

export default async function Meta() {
  // const matchups: MatchupData[] = await matchupPerformance();
  // console.log(JSON.stringify(matchups));
  // const serverStats = await getServerStats({ category: "ranked" });
  // console.log(JSON.stringify(serverStats));
  return <MetaPage data={matchups} />;
}
