import { MetaPage } from "@/spaces/meta/MetaPage";
import type { MatchupData } from "@/spaces/meta/types";

export const dynamicParams = false;
export const dynamic = "force-static";
export const fetchCache = "force-cache";

const matchups: MatchupData[] = [
  {
    deck: "amber/amethyst",
    versus: "amber/steel",
    total_matches: "685",
    wins: "173",
    overall_winrate: "25.26",
    wins_on_play: "104",
    matches_on_play: "345",
    play_winrate: "30.14",
    wins_on_draw: "69",
    matches_on_draw: "340",
    draw_winrate: "20.29",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/ruby",
    total_matches: "651",
    wins: "355",
    overall_winrate: "54.53",
    wins_on_play: "199",
    matches_on_play: "321",
    play_winrate: "61.99",
    wins_on_draw: "156",
    matches_on_draw: "330",
    draw_winrate: "47.27",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/sapphire",
    total_matches: "602",
    wins: "361",
    overall_winrate: "59.97",
    wins_on_play: "213",
    matches_on_play: "302",
    play_winrate: "70.53",
    wins_on_draw: "148",
    matches_on_draw: "300",
    draw_winrate: "49.33",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/emerald",
    total_matches: "449",
    wins: "199",
    overall_winrate: "44.32",
    wins_on_play: "122",
    matches_on_play: "233",
    play_winrate: "52.36",
    wins_on_draw: "77",
    matches_on_draw: "216",
    draw_winrate: "35.65",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/steel",
    total_matches: "444",
    wins: "169",
    overall_winrate: "38.06",
    wins_on_play: "109",
    matches_on_play: "236",
    play_winrate: "46.19",
    wins_on_draw: "60",
    matches_on_draw: "208",
    draw_winrate: "28.85",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "steel/emerald",
    total_matches: "282",
    wins: "81",
    overall_winrate: "28.72",
    wins_on_play: "50",
    matches_on_play: "136",
    play_winrate: "36.76",
    wins_on_draw: "31",
    matches_on_draw: "146",
    draw_winrate: "21.23",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "sapphire/steel",
    total_matches: "264",
    wins: "139",
    overall_winrate: "52.65",
    wins_on_play: "78",
    matches_on_play: "129",
    play_winrate: "60.47",
    wins_on_draw: "61",
    matches_on_draw: "135",
    draw_winrate: "45.19",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/sapphire",
    total_matches: "214",
    wins: "104",
    overall_winrate: "48.60",
    wins_on_play: "62",
    matches_on_play: "108",
    play_winrate: "57.41",
    wins_on_draw: "42",
    matches_on_draw: "106",
    draw_winrate: "39.62",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/ruby",
    total_matches: "91",
    wins: "50",
    overall_winrate: "54.95",
    wins_on_play: "25",
    matches_on_play: "45",
    play_winrate: "55.56",
    wins_on_draw: "25",
    matches_on_draw: "46",
    draw_winrate: "54.35",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/amethyst",
    total_matches: "88",
    wins: "88",
    overall_winrate: "100.00",
    wins_on_play: "76",
    matches_on_play: "76",
    play_winrate: "100.00",
    wins_on_draw: "72",
    matches_on_draw: "72",
    draw_winrate: "100.00",
    mirror_matches: "88",
  },
  {
    deck: "amber/amethyst",
    versus: "sapphire/emerald",
    total_matches: "81",
    wins: "51",
    overall_winrate: "62.96",
    wins_on_play: "25",
    matches_on_play: "37",
    play_winrate: "67.57",
    wins_on_draw: "26",
    matches_on_draw: "44",
    draw_winrate: "59.09",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/emerald",
    total_matches: "65",
    wins: "33",
    overall_winrate: "50.77",
    wins_on_play: "22",
    matches_on_play: "36",
    play_winrate: "61.11",
    wins_on_draw: "11",
    matches_on_draw: "29",
    draw_winrate: "37.93",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/steel",
    total_matches: "63",
    wins: "22",
    overall_winrate: "34.92",
    wins_on_play: "7",
    matches_on_play: "24",
    play_winrate: "29.17",
    wins_on_draw: "15",
    matches_on_draw: "39",
    draw_winrate: "38.46",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/emerald",
    total_matches: "35",
    wins: "19",
    overall_winrate: "54.29",
    wins_on_play: "10",
    matches_on_play: "15",
    play_winrate: "66.67",
    wins_on_draw: "9",
    matches_on_draw: "20",
    draw_winrate: "45.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/sapphire",
    total_matches: "32",
    wins: "16",
    overall_winrate: "50.00",
    wins_on_play: "8",
    matches_on_play: "14",
    play_winrate: "57.14",
    wins_on_draw: "8",
    matches_on_draw: "18",
    draw_winrate: "44.44",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/steel",
    total_matches: "732",
    wins: "239",
    overall_winrate: "32.65",
    wins_on_play: "137",
    matches_on_play: "353",
    play_winrate: "38.81",
    wins_on_draw: "102",
    matches_on_draw: "379",
    draw_winrate: "26.91",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/ruby",
    total_matches: "712",
    wins: "321",
    overall_winrate: "45.08",
    wins_on_play: "198",
    matches_on_play: "367",
    play_winrate: "53.95",
    wins_on_draw: "123",
    matches_on_draw: "345",
    draw_winrate: "35.65",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/sapphire",
    total_matches: "668",
    wins: "360",
    overall_winrate: "53.89",
    wins_on_play: "201",
    matches_on_play: "334",
    play_winrate: "60.18",
    wins_on_draw: "159",
    matches_on_draw: "334",
    draw_winrate: "47.60",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/emerald",
    total_matches: "498",
    wins: "206",
    overall_winrate: "41.37",
    wins_on_play: "138",
    matches_on_play: "270",
    play_winrate: "51.11",
    wins_on_draw: "68",
    matches_on_draw: "228",
    draw_winrate: "29.82",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/steel",
    total_matches: "473",
    wins: "176",
    overall_winrate: "37.21",
    wins_on_play: "95",
    matches_on_play: "238",
    play_winrate: "39.92",
    wins_on_draw: "81",
    matches_on_draw: "235",
    draw_winrate: "34.47",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "steel/emerald",
    total_matches: "322",
    wins: "108",
    overall_winrate: "33.54",
    wins_on_play: "56",
    matches_on_play: "151",
    play_winrate: "37.09",
    wins_on_draw: "52",
    matches_on_draw: "171",
    draw_winrate: "30.41",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "sapphire/steel",
    total_matches: "282",
    wins: "129",
    overall_winrate: "45.74",
    wins_on_play: "73",
    matches_on_play: "143",
    play_winrate: "51.05",
    wins_on_draw: "56",
    matches_on_draw: "139",
    draw_winrate: "40.29",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/sapphire",
    total_matches: "268",
    wins: "134",
    overall_winrate: "50.00",
    wins_on_play: "77",
    matches_on_play: "124",
    play_winrate: "62.10",
    wins_on_draw: "57",
    matches_on_draw: "144",
    draw_winrate: "39.58",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/emerald",
    total_matches: "98",
    wins: "98",
    overall_winrate: "100.00",
    wins_on_play: "88",
    matches_on_play: "88",
    play_winrate: "100.00",
    wins_on_draw: "73",
    matches_on_draw: "73",
    draw_winrate: "100.00",
    mirror_matches: "98",
  },
  {
    deck: "amber/emerald",
    versus: "sapphire/emerald",
    total_matches: "88",
    wins: "49",
    overall_winrate: "55.68",
    wins_on_play: "30",
    matches_on_play: "44",
    play_winrate: "68.18",
    wins_on_draw: "19",
    matches_on_draw: "44",
    draw_winrate: "43.18",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/ruby",
    total_matches: "83",
    wins: "46",
    overall_winrate: "55.42",
    wins_on_play: "25",
    matches_on_play: "39",
    play_winrate: "64.10",
    wins_on_draw: "21",
    matches_on_draw: "44",
    draw_winrate: "47.73",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/amethyst",
    total_matches: "65",
    wins: "32",
    overall_winrate: "49.23",
    wins_on_play: "18",
    matches_on_play: "29",
    play_winrate: "62.07",
    wins_on_draw: "14",
    matches_on_draw: "36",
    draw_winrate: "38.89",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/steel",
    total_matches: "59",
    wins: "29",
    overall_winrate: "49.15",
    wins_on_play: "14",
    matches_on_play: "29",
    play_winrate: "48.28",
    wins_on_draw: "15",
    matches_on_draw: "30",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/emerald",
    total_matches: "45",
    wins: "27",
    overall_winrate: "60.00",
    wins_on_play: "17",
    matches_on_play: "27",
    play_winrate: "62.96",
    wins_on_draw: "10",
    matches_on_draw: "18",
    draw_winrate: "55.56",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/sapphire",
    total_matches: "30",
    wins: "18",
    overall_winrate: "60.00",
    wins_on_play: "8",
    matches_on_play: "15",
    play_winrate: "53.33",
    wins_on_draw: "10",
    matches_on_draw: "15",
    draw_winrate: "66.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "steel",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/steel",
    total_matches: "791",
    wins: "236",
    overall_winrate: "29.84",
    wins_on_play: "136",
    matches_on_play: "381",
    play_winrate: "35.70",
    wins_on_draw: "100",
    matches_on_draw: "410",
    draw_winrate: "24.39",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/ruby",
    total_matches: "787",
    wins: "315",
    overall_winrate: "40.03",
    wins_on_play: "165",
    matches_on_play: "397",
    play_winrate: "41.56",
    wins_on_draw: "150",
    matches_on_draw: "390",
    draw_winrate: "38.46",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/sapphire",
    total_matches: "643",
    wins: "262",
    overall_winrate: "40.75",
    wins_on_play: "139",
    matches_on_play: "302",
    play_winrate: "46.03",
    wins_on_draw: "123",
    matches_on_draw: "341",
    draw_winrate: "36.07",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/steel",
    total_matches: "547",
    wins: "211",
    overall_winrate: "38.57",
    wins_on_play: "120",
    matches_on_play: "286",
    play_winrate: "41.96",
    wins_on_draw: "91",
    matches_on_draw: "261",
    draw_winrate: "34.87",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/emerald",
    total_matches: "535",
    wins: "219",
    overall_winrate: "40.93",
    wins_on_play: "122",
    matches_on_play: "247",
    play_winrate: "49.39",
    wins_on_draw: "97",
    matches_on_draw: "288",
    draw_winrate: "33.68",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "sapphire/steel",
    total_matches: "344",
    wins: "164",
    overall_winrate: "47.67",
    wins_on_play: "84",
    matches_on_play: "161",
    play_winrate: "52.17",
    wins_on_draw: "80",
    matches_on_draw: "183",
    draw_winrate: "43.72",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "steel/emerald",
    total_matches: "329",
    wins: "116",
    overall_winrate: "35.26",
    wins_on_play: "72",
    matches_on_play: "175",
    play_winrate: "41.14",
    wins_on_draw: "44",
    matches_on_draw: "154",
    draw_winrate: "28.57",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/sapphire",
    total_matches: "241",
    wins: "81",
    overall_winrate: "33.61",
    wins_on_play: "39",
    matches_on_play: "105",
    play_winrate: "37.14",
    wins_on_draw: "42",
    matches_on_draw: "136",
    draw_winrate: "30.88",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "sapphire/emerald",
    total_matches: "116",
    wins: "67",
    overall_winrate: "57.76",
    wins_on_play: "35",
    matches_on_play: "54",
    play_winrate: "64.81",
    wins_on_draw: "32",
    matches_on_draw: "62",
    draw_winrate: "51.61",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/ruby",
    total_matches: "100",
    wins: "100",
    overall_winrate: "100.00",
    wins_on_play: "76",
    matches_on_play: "76",
    play_winrate: "100.00",
    wins_on_draw: "72",
    matches_on_draw: "72",
    draw_winrate: "100.00",
    mirror_matches: "100",
  },
  {
    deck: "amber/ruby",
    versus: "amber/amethyst",
    total_matches: "91",
    wins: "41",
    overall_winrate: "45.05",
    wins_on_play: "21",
    matches_on_play: "46",
    play_winrate: "45.65",
    wins_on_draw: "20",
    matches_on_draw: "45",
    draw_winrate: "44.44",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/emerald",
    total_matches: "83",
    wins: "37",
    overall_winrate: "44.58",
    wins_on_play: "23",
    matches_on_play: "44",
    play_winrate: "52.27",
    wins_on_draw: "14",
    matches_on_draw: "39",
    draw_winrate: "35.90",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/steel",
    total_matches: "75",
    wins: "33",
    overall_winrate: "44.00",
    wins_on_play: "16",
    matches_on_play: "40",
    play_winrate: "40.00",
    wins_on_draw: "17",
    matches_on_draw: "35",
    draw_winrate: "48.57",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/emerald",
    total_matches: "52",
    wins: "31",
    overall_winrate: "59.62",
    wins_on_play: "14",
    matches_on_play: "22",
    play_winrate: "63.64",
    wins_on_draw: "17",
    matches_on_draw: "30",
    draw_winrate: "56.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/sapphire",
    total_matches: "49",
    wins: "30",
    overall_winrate: "61.22",
    wins_on_play: "14",
    matches_on_play: "22",
    play_winrate: "63.64",
    wins_on_draw: "16",
    matches_on_draw: "27",
    draw_winrate: "59.26",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/steel",
    total_matches: "383",
    wins: "95",
    overall_winrate: "24.80",
    wins_on_play: "57",
    matches_on_play: "204",
    play_winrate: "27.94",
    wins_on_draw: "38",
    matches_on_draw: "179",
    draw_winrate: "21.23",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/ruby",
    total_matches: "317",
    wins: "122",
    overall_winrate: "38.49",
    wins_on_play: "72",
    matches_on_play: "159",
    play_winrate: "45.28",
    wins_on_draw: "50",
    matches_on_draw: "158",
    draw_winrate: "31.65",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/sapphire",
    total_matches: "285",
    wins: "140",
    overall_winrate: "49.12",
    wins_on_play: "95",
    matches_on_play: "153",
    play_winrate: "62.09",
    wins_on_draw: "45",
    matches_on_draw: "132",
    draw_winrate: "34.09",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/steel",
    total_matches: "253",
    wins: "85",
    overall_winrate: "33.60",
    wins_on_play: "44",
    matches_on_play: "118",
    play_winrate: "37.29",
    wins_on_draw: "41",
    matches_on_draw: "135",
    draw_winrate: "30.37",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/emerald",
    total_matches: "236",
    wins: "80",
    overall_winrate: "33.90",
    wins_on_play: "55",
    matches_on_play: "114",
    play_winrate: "48.25",
    wins_on_draw: "25",
    matches_on_draw: "122",
    draw_winrate: "20.49",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "steel/emerald",
    total_matches: "142",
    wins: "54",
    overall_winrate: "38.03",
    wins_on_play: "29",
    matches_on_play: "69",
    play_winrate: "42.03",
    wins_on_draw: "25",
    matches_on_draw: "73",
    draw_winrate: "34.25",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire/steel",
    total_matches: "134",
    wins: "76",
    overall_winrate: "56.72",
    wins_on_play: "40",
    matches_on_play: "67",
    play_winrate: "59.70",
    wins_on_draw: "36",
    matches_on_draw: "67",
    draw_winrate: "53.73",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "102",
    wins: "37",
    overall_winrate: "36.27",
    wins_on_play: "21",
    matches_on_play: "50",
    play_winrate: "42.00",
    wins_on_draw: "16",
    matches_on_draw: "52",
    draw_winrate: "30.77",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/ruby",
    total_matches: "49",
    wins: "19",
    overall_winrate: "38.78",
    wins_on_play: "11",
    matches_on_play: "27",
    play_winrate: "40.74",
    wins_on_draw: "8",
    matches_on_draw: "22",
    draw_winrate: "36.36",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire/emerald",
    total_matches: "41",
    wins: "21",
    overall_winrate: "51.22",
    wins_on_play: "13",
    matches_on_play: "19",
    play_winrate: "68.42",
    wins_on_draw: "8",
    matches_on_draw: "22",
    draw_winrate: "36.36",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/sapphire",
    total_matches: "35",
    wins: "35",
    overall_winrate: "100.00",
    wins_on_play: "32",
    matches_on_play: "32",
    play_winrate: "100.00",
    wins_on_draw: "28",
    matches_on_draw: "28",
    draw_winrate: "100.00",
    mirror_matches: "35",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/amethyst",
    total_matches: "32",
    wins: "16",
    overall_winrate: "50.00",
    wins_on_play: "10",
    matches_on_play: "18",
    play_winrate: "55.56",
    wins_on_draw: "6",
    matches_on_draw: "14",
    draw_winrate: "42.86",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/emerald",
    total_matches: "30",
    wins: "12",
    overall_winrate: "40.00",
    wins_on_play: "5",
    matches_on_play: "15",
    play_winrate: "33.33",
    wins_on_draw: "7",
    matches_on_draw: "15",
    draw_winrate: "46.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/steel",
    total_matches: "26",
    wins: "9",
    overall_winrate: "34.62",
    wins_on_play: "6",
    matches_on_play: "13",
    play_winrate: "46.15",
    wins_on_draw: "3",
    matches_on_draw: "13",
    draw_winrate: "23.08",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/emerald",
    total_matches: "21",
    wins: "15",
    overall_winrate: "71.43",
    wins_on_play: "10",
    matches_on_play: "13",
    play_winrate: "76.92",
    wins_on_draw: "5",
    matches_on_draw: "8",
    draw_winrate: "62.50",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/sapphire",
    total_matches: "7917",
    wins: "3259",
    overall_winrate: "41.16",
    wins_on_play: "1946",
    matches_on_play: "4027",
    play_winrate: "48.32",
    wins_on_draw: "1313",
    matches_on_draw: "3890",
    draw_winrate: "33.75",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/ruby",
    total_matches: "7728",
    wins: "4292",
    overall_winrate: "55.54",
    wins_on_play: "2509",
    matches_on_play: "3932",
    play_winrate: "63.81",
    wins_on_draw: "1783",
    matches_on_draw: "3796",
    draw_winrate: "46.97",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/emerald",
    total_matches: "6030",
    wins: "3640",
    overall_winrate: "60.36",
    wins_on_play: "2013",
    matches_on_play: "3006",
    play_winrate: "66.97",
    wins_on_draw: "1627",
    matches_on_draw: "3024",
    draw_winrate: "53.80",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/steel",
    total_matches: "5590",
    wins: "3014",
    overall_winrate: "53.92",
    wins_on_play: "1647",
    matches_on_play: "2781",
    play_winrate: "59.22",
    wins_on_draw: "1367",
    matches_on_draw: "2809",
    draw_winrate: "48.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/steel",
    total_matches: "5004",
    wins: "5004",
    overall_winrate: "100.00",
    wins_on_play: "3086",
    matches_on_play: "3086",
    play_winrate: "100.00",
    wins_on_draw: "2449",
    matches_on_draw: "2449",
    draw_winrate: "100.00",
    mirror_matches: "5004",
  },
  {
    deck: "amber/steel",
    versus: "steel/emerald",
    total_matches: "3549",
    wins: "1891",
    overall_winrate: "53.28",
    wins_on_play: "1004",
    matches_on_play: "1725",
    play_winrate: "58.20",
    wins_on_draw: "887",
    matches_on_draw: "1824",
    draw_winrate: "48.63",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire/steel",
    total_matches: "3208",
    wins: "1864",
    overall_winrate: "58.10",
    wins_on_play: "1025",
    matches_on_play: "1591",
    play_winrate: "64.42",
    wins_on_draw: "839",
    matches_on_draw: "1617",
    draw_winrate: "51.89",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/sapphire",
    total_matches: "2939",
    wins: "1662",
    overall_winrate: "56.55",
    wins_on_play: "905",
    matches_on_play: "1428",
    play_winrate: "63.38",
    wins_on_draw: "757",
    matches_on_draw: "1511",
    draw_winrate: "50.10",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire/emerald",
    total_matches: "954",
    wins: "691",
    overall_winrate: "72.43",
    wins_on_play: "376",
    matches_on_play: "475",
    play_winrate: "79.16",
    wins_on_draw: "315",
    matches_on_draw: "479",
    draw_winrate: "65.76",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/ruby",
    total_matches: "791",
    wins: "555",
    overall_winrate: "70.16",
    wins_on_play: "310",
    matches_on_play: "410",
    play_winrate: "75.61",
    wins_on_draw: "245",
    matches_on_draw: "381",
    draw_winrate: "64.30",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/emerald",
    total_matches: "732",
    wins: "493",
    overall_winrate: "67.35",
    wins_on_play: "277",
    matches_on_play: "379",
    play_winrate: "73.09",
    wins_on_draw: "216",
    matches_on_draw: "353",
    draw_winrate: "61.19",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/amethyst",
    total_matches: "685",
    wins: "512",
    overall_winrate: "74.74",
    wins_on_play: "271",
    matches_on_play: "340",
    play_winrate: "79.71",
    wins_on_draw: "241",
    matches_on_draw: "345",
    draw_winrate: "69.86",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/steel",
    total_matches: "435",
    wins: "270",
    overall_winrate: "62.07",
    wins_on_play: "152",
    matches_on_play: "214",
    play_winrate: "71.03",
    wins_on_draw: "118",
    matches_on_draw: "221",
    draw_winrate: "53.39",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/sapphire",
    total_matches: "383",
    wins: "288",
    overall_winrate: "75.20",
    wins_on_play: "141",
    matches_on_play: "179",
    play_winrate: "78.77",
    wins_on_draw: "147",
    matches_on_draw: "204",
    draw_winrate: "72.06",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/emerald",
    total_matches: "282",
    wins: "211",
    overall_winrate: "74.82",
    wins_on_play: "104",
    matches_on_play: "134",
    play_winrate: "77.61",
    wins_on_draw: "107",
    matches_on_draw: "148",
    draw_winrate: "72.30",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "2",
    matches_on_play: "2",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "steel",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "2",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/steel",
    total_matches: "6030",
    wins: "2390",
    overall_winrate: "39.64",
    wins_on_play: "1397",
    matches_on_play: "3024",
    play_winrate: "46.20",
    wins_on_draw: "993",
    matches_on_draw: "3006",
    draw_winrate: "33.03",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/ruby",
    total_matches: "5470",
    wins: "3270",
    overall_winrate: "59.78",
    wins_on_play: "1847",
    matches_on_play: "2770",
    play_winrate: "66.68",
    wins_on_draw: "1423",
    matches_on_draw: "2700",
    draw_winrate: "52.70",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/sapphire",
    total_matches: "5375",
    wins: "3313",
    overall_winrate: "61.64",
    wins_on_play: "1879",
    matches_on_play: "2742",
    play_winrate: "68.53",
    wins_on_draw: "1434",
    matches_on_draw: "2633",
    draw_winrate: "54.46",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/steel",
    total_matches: "3848",
    wins: "1508",
    overall_winrate: "39.19",
    wins_on_play: "934",
    matches_on_play: "1982",
    play_winrate: "47.12",
    wins_on_draw: "574",
    matches_on_draw: "1866",
    draw_winrate: "30.76",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/emerald",
    total_matches: "2567",
    wins: "2567",
    overall_winrate: "100.00",
    wins_on_play: "1641",
    matches_on_play: "1641",
    play_winrate: "100.00",
    wins_on_draw: "1346",
    matches_on_draw: "1346",
    draw_winrate: "100.00",
    mirror_matches: "2567",
  },
  {
    deck: "amethyst/emerald",
    versus: "steel/emerald",
    total_matches: "2351",
    wins: "1090",
    overall_winrate: "46.36",
    wins_on_play: "597",
    matches_on_play: "1131",
    play_winrate: "52.79",
    wins_on_draw: "493",
    matches_on_draw: "1220",
    draw_winrate: "40.41",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire/steel",
    total_matches: "2187",
    wins: "989",
    overall_winrate: "45.22",
    wins_on_play: "570",
    matches_on_play: "1085",
    play_winrate: "52.53",
    wins_on_draw: "419",
    matches_on_draw: "1102",
    draw_winrate: "38.02",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/sapphire",
    total_matches: "2070",
    wins: "1061",
    overall_winrate: "51.26",
    wins_on_play: "595",
    matches_on_play: "1005",
    play_winrate: "59.20",
    wins_on_draw: "466",
    matches_on_draw: "1065",
    draw_winrate: "43.76",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire/emerald",
    total_matches: "690",
    wins: "487",
    overall_winrate: "70.58",
    wins_on_play: "262",
    matches_on_play: "347",
    play_winrate: "75.50",
    wins_on_draw: "225",
    matches_on_draw: "343",
    draw_winrate: "65.60",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/ruby",
    total_matches: "535",
    wins: "316",
    overall_winrate: "59.07",
    wins_on_play: "191",
    matches_on_play: "288",
    play_winrate: "66.32",
    wins_on_draw: "125",
    matches_on_draw: "247",
    draw_winrate: "50.61",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/emerald",
    total_matches: "498",
    wins: "292",
    overall_winrate: "58.63",
    wins_on_play: "160",
    matches_on_play: "228",
    play_winrate: "70.18",
    wins_on_draw: "132",
    matches_on_draw: "270",
    draw_winrate: "48.89",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/amethyst",
    total_matches: "449",
    wins: "250",
    overall_winrate: "55.68",
    wins_on_play: "139",
    matches_on_play: "216",
    play_winrate: "64.35",
    wins_on_draw: "111",
    matches_on_draw: "233",
    draw_winrate: "47.64",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/steel",
    total_matches: "316",
    wins: "181",
    overall_winrate: "57.28",
    wins_on_play: "108",
    matches_on_play: "177",
    play_winrate: "61.02",
    wins_on_draw: "73",
    matches_on_draw: "139",
    draw_winrate: "52.52",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/sapphire",
    total_matches: "236",
    wins: "156",
    overall_winrate: "66.10",
    wins_on_play: "97",
    matches_on_play: "122",
    play_winrate: "79.51",
    wins_on_draw: "59",
    matches_on_draw: "114",
    draw_winrate: "51.75",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/emerald",
    total_matches: "228",
    wins: "162",
    overall_winrate: "71.05",
    wins_on_play: "76",
    matches_on_play: "102",
    play_winrate: "74.51",
    wins_on_draw: "86",
    matches_on_draw: "126",
    draw_winrate: "68.25",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "emerald",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/steel",
    total_matches: "7728",
    wins: "3436",
    overall_winrate: "44.46",
    wins_on_play: "2013",
    matches_on_play: "3796",
    play_winrate: "53.03",
    wins_on_draw: "1423",
    matches_on_draw: "3932",
    draw_winrate: "36.19",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/sapphire",
    total_matches: "6779",
    wins: "3704",
    overall_winrate: "54.64",
    wins_on_play: "2083",
    matches_on_play: "3370",
    play_winrate: "61.81",
    wins_on_draw: "1621",
    matches_on_draw: "3409",
    draw_winrate: "47.55",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/emerald",
    total_matches: "5470",
    wins: "2200",
    overall_winrate: "40.22",
    wins_on_play: "1277",
    matches_on_play: "2700",
    play_winrate: "47.30",
    wins_on_draw: "923",
    matches_on_draw: "2770",
    draw_winrate: "33.32",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/steel",
    total_matches: "5233",
    wins: "2483",
    overall_winrate: "47.45",
    wins_on_play: "1436",
    matches_on_play: "2632",
    play_winrate: "54.56",
    wins_on_draw: "1047",
    matches_on_draw: "2601",
    draw_winrate: "40.25",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/ruby",
    total_matches: "4231",
    wins: "4231",
    overall_winrate: "100.00",
    wins_on_play: "2675",
    matches_on_play: "2675",
    play_winrate: "100.00",
    wins_on_draw: "2078",
    matches_on_draw: "2078",
    draw_winrate: "100.00",
    mirror_matches: "4231",
  },
  {
    deck: "amethyst/ruby",
    versus: "steel/emerald",
    total_matches: "3227",
    wins: "1701",
    overall_winrate: "52.71",
    wins_on_play: "898",
    matches_on_play: "1600",
    play_winrate: "56.13",
    wins_on_draw: "803",
    matches_on_draw: "1627",
    draw_winrate: "49.35",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire/steel",
    total_matches: "2901",
    wins: "1661",
    overall_winrate: "57.26",
    wins_on_play: "953",
    matches_on_play: "1492",
    play_winrate: "63.87",
    wins_on_draw: "708",
    matches_on_draw: "1409",
    draw_winrate: "50.25",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/sapphire",
    total_matches: "2587",
    wins: "1292",
    overall_winrate: "49.94",
    wins_on_play: "774",
    matches_on_play: "1331",
    play_winrate: "58.15",
    wins_on_draw: "518",
    matches_on_draw: "1256",
    draw_winrate: "41.24",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire/emerald",
    total_matches: "888",
    wins: "459",
    overall_winrate: "51.69",
    wins_on_play: "245",
    matches_on_play: "425",
    play_winrate: "57.65",
    wins_on_draw: "214",
    matches_on_draw: "463",
    draw_winrate: "46.22",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/ruby",
    total_matches: "787",
    wins: "472",
    overall_winrate: "59.97",
    wins_on_play: "240",
    matches_on_play: "390",
    play_winrate: "61.54",
    wins_on_draw: "232",
    matches_on_draw: "397",
    draw_winrate: "58.44",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/emerald",
    total_matches: "712",
    wins: "391",
    overall_winrate: "54.92",
    wins_on_play: "222",
    matches_on_play: "345",
    play_winrate: "64.35",
    wins_on_draw: "169",
    matches_on_draw: "367",
    draw_winrate: "46.05",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/amethyst",
    total_matches: "651",
    wins: "296",
    overall_winrate: "45.47",
    wins_on_play: "174",
    matches_on_play: "330",
    play_winrate: "52.73",
    wins_on_draw: "122",
    matches_on_draw: "321",
    draw_winrate: "38.01",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/steel",
    total_matches: "428",
    wins: "292",
    overall_winrate: "68.22",
    wins_on_play: "164",
    matches_on_play: "227",
    play_winrate: "72.25",
    wins_on_draw: "128",
    matches_on_draw: "201",
    draw_winrate: "63.68",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/sapphire",
    total_matches: "317",
    wins: "195",
    overall_winrate: "61.51",
    wins_on_play: "108",
    matches_on_play: "158",
    play_winrate: "68.35",
    wins_on_draw: "87",
    matches_on_draw: "159",
    draw_winrate: "54.72",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/emerald",
    total_matches: "305",
    wins: "185",
    overall_winrate: "60.66",
    wins_on_play: "103",
    matches_on_play: "156",
    play_winrate: "66.03",
    wins_on_draw: "82",
    matches_on_draw: "149",
    draw_winrate: "55.03",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "steel",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "1",
    play_winrate: "0.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/steel",
    total_matches: "2939",
    wins: "1277",
    overall_winrate: "43.45",
    wins_on_play: "754",
    matches_on_play: "1511",
    play_winrate: "49.90",
    wins_on_draw: "523",
    matches_on_draw: "1428",
    draw_winrate: "36.62",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/sapphire",
    total_matches: "2700",
    wins: "1234",
    overall_winrate: "45.70",
    wins_on_play: "709",
    matches_on_play: "1356",
    play_winrate: "52.29",
    wins_on_draw: "525",
    matches_on_draw: "1344",
    draw_winrate: "39.06",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/ruby",
    total_matches: "2587",
    wins: "1295",
    overall_winrate: "50.06",
    wins_on_play: "738",
    matches_on_play: "1256",
    play_winrate: "58.76",
    wins_on_draw: "557",
    matches_on_draw: "1331",
    draw_winrate: "41.85",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/emerald",
    total_matches: "2070",
    wins: "1009",
    overall_winrate: "48.74",
    wins_on_play: "599",
    matches_on_play: "1065",
    play_winrate: "56.24",
    wins_on_draw: "410",
    matches_on_draw: "1005",
    draw_winrate: "40.80",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/steel",
    total_matches: "1915",
    wins: "1043",
    overall_winrate: "54.46",
    wins_on_play: "592",
    matches_on_play: "939",
    play_winrate: "63.05",
    wins_on_draw: "451",
    matches_on_draw: "976",
    draw_winrate: "46.21",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "steel/emerald",
    total_matches: "1177",
    wins: "546",
    overall_winrate: "46.39",
    wins_on_play: "297",
    matches_on_play: "593",
    play_winrate: "50.08",
    wins_on_draw: "249",
    matches_on_draw: "584",
    draw_winrate: "42.64",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "sapphire/steel",
    total_matches: "1051",
    wins: "603",
    overall_winrate: "57.37",
    wins_on_play: "342",
    matches_on_play: "526",
    play_winrate: "65.02",
    wins_on_draw: "261",
    matches_on_draw: "525",
    draw_winrate: "49.71",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "630",
    wins: "630",
    overall_winrate: "100.00",
    wins_on_play: "428",
    matches_on_play: "428",
    play_winrate: "100.00",
    wins_on_draw: "357",
    matches_on_draw: "357",
    draw_winrate: "100.00",
    mirror_matches: "630",
  },
  {
    deck: "amethyst/sapphire",
    versus: "sapphire/emerald",
    total_matches: "377",
    wins: "204",
    overall_winrate: "54.11",
    wins_on_play: "99",
    matches_on_play: "179",
    play_winrate: "55.31",
    wins_on_draw: "105",
    matches_on_draw: "198",
    draw_winrate: "53.03",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/emerald",
    total_matches: "268",
    wins: "134",
    overall_winrate: "50.00",
    wins_on_play: "87",
    matches_on_play: "144",
    play_winrate: "60.42",
    wins_on_draw: "47",
    matches_on_draw: "124",
    draw_winrate: "37.90",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/ruby",
    total_matches: "241",
    wins: "160",
    overall_winrate: "66.39",
    wins_on_play: "94",
    matches_on_play: "136",
    play_winrate: "69.12",
    wins_on_draw: "66",
    matches_on_draw: "105",
    draw_winrate: "62.86",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/amethyst",
    total_matches: "214",
    wins: "110",
    overall_winrate: "51.40",
    wins_on_play: "64",
    matches_on_play: "106",
    play_winrate: "60.38",
    wins_on_draw: "46",
    matches_on_draw: "108",
    draw_winrate: "42.59",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/steel",
    total_matches: "135",
    wins: "96",
    overall_winrate: "71.11",
    wins_on_play: "49",
    matches_on_play: "66",
    play_winrate: "74.24",
    wins_on_draw: "47",
    matches_on_draw: "69",
    draw_winrate: "68.12",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/sapphire",
    total_matches: "102",
    wins: "65",
    overall_winrate: "63.73",
    wins_on_play: "36",
    matches_on_play: "52",
    play_winrate: "69.23",
    wins_on_draw: "29",
    matches_on_draw: "50",
    draw_winrate: "58.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/emerald",
    total_matches: "100",
    wins: "64",
    overall_winrate: "64.00",
    wins_on_play: "35",
    matches_on_play: "52",
    play_winrate: "67.31",
    wins_on_draw: "29",
    matches_on_draw: "48",
    draw_winrate: "60.42",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "emerald",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/steel",
    total_matches: "5590",
    wins: "2576",
    overall_winrate: "46.08",
    wins_on_play: "1442",
    matches_on_play: "2809",
    play_winrate: "51.33",
    wins_on_draw: "1134",
    matches_on_draw: "2781",
    draw_winrate: "40.78",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/ruby",
    total_matches: "5233",
    wins: "2750",
    overall_winrate: "52.55",
    wins_on_play: "1554",
    matches_on_play: "2601",
    play_winrate: "59.75",
    wins_on_draw: "1196",
    matches_on_draw: "2632",
    draw_winrate: "45.44",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/sapphire",
    total_matches: "5079",
    wins: "2433",
    overall_winrate: "47.90",
    wins_on_play: "1355",
    matches_on_play: "2489",
    play_winrate: "54.44",
    wins_on_draw: "1078",
    matches_on_draw: "2590",
    draw_winrate: "41.62",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/emerald",
    total_matches: "3848",
    wins: "2340",
    overall_winrate: "60.81",
    wins_on_play: "1292",
    matches_on_play: "1866",
    play_winrate: "69.24",
    wins_on_draw: "1048",
    matches_on_draw: "1982",
    draw_winrate: "52.88",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/steel",
    total_matches: "2315",
    wins: "2315",
    overall_winrate: "100.00",
    wins_on_play: "1463",
    matches_on_play: "1463",
    play_winrate: "100.00",
    wins_on_draw: "1267",
    matches_on_draw: "1267",
    draw_winrate: "100.00",
    mirror_matches: "2315",
  },
  {
    deck: "amethyst/steel",
    versus: "steel/emerald",
    total_matches: "2248",
    wins: "1169",
    overall_winrate: "52.00",
    wins_on_play: "636",
    matches_on_play: "1153",
    play_winrate: "55.16",
    wins_on_draw: "533",
    matches_on_draw: "1095",
    draw_winrate: "48.68",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire/steel",
    total_matches: "2067",
    wins: "1037",
    overall_winrate: "50.17",
    wins_on_play: "598",
    matches_on_play: "1049",
    play_winrate: "57.01",
    wins_on_draw: "439",
    matches_on_draw: "1018",
    draw_winrate: "43.12",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/sapphire",
    total_matches: "1915",
    wins: "872",
    overall_winrate: "45.54",
    wins_on_play: "525",
    matches_on_play: "976",
    play_winrate: "53.79",
    wins_on_draw: "347",
    matches_on_draw: "939",
    draw_winrate: "36.95",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire/emerald",
    total_matches: "643",
    wins: "422",
    overall_winrate: "65.63",
    wins_on_play: "234",
    matches_on_play: "328",
    play_winrate: "71.34",
    wins_on_draw: "188",
    matches_on_draw: "315",
    draw_winrate: "59.68",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/ruby",
    total_matches: "547",
    wins: "336",
    overall_winrate: "61.43",
    wins_on_play: "170",
    matches_on_play: "261",
    play_winrate: "65.13",
    wins_on_draw: "166",
    matches_on_draw: "286",
    draw_winrate: "58.04",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/emerald",
    total_matches: "473",
    wins: "297",
    overall_winrate: "62.79",
    wins_on_play: "154",
    matches_on_play: "235",
    play_winrate: "65.53",
    wins_on_draw: "143",
    matches_on_draw: "238",
    draw_winrate: "60.08",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/amethyst",
    total_matches: "444",
    wins: "275",
    overall_winrate: "61.94",
    wins_on_play: "148",
    matches_on_play: "208",
    play_winrate: "71.15",
    wins_on_draw: "127",
    matches_on_draw: "236",
    draw_winrate: "53.81",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/steel",
    total_matches: "286",
    wins: "187",
    overall_winrate: "65.38",
    wins_on_play: "98",
    matches_on_play: "143",
    play_winrate: "68.53",
    wins_on_draw: "89",
    matches_on_draw: "143",
    draw_winrate: "62.24",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/sapphire",
    total_matches: "253",
    wins: "168",
    overall_winrate: "66.40",
    wins_on_play: "94",
    matches_on_play: "135",
    play_winrate: "69.63",
    wins_on_draw: "74",
    matches_on_draw: "118",
    draw_winrate: "62.71",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/emerald",
    total_matches: "194",
    wins: "151",
    overall_winrate: "77.84",
    wins_on_play: "81",
    matches_on_play: "104",
    play_winrate: "77.88",
    wins_on_draw: "70",
    matches_on_draw: "90",
    draw_winrate: "77.78",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/ruby",
    total_matches: "305",
    wins: "120",
    overall_winrate: "39.34",
    wins_on_play: "67",
    matches_on_play: "149",
    play_winrate: "44.97",
    wins_on_draw: "53",
    matches_on_draw: "156",
    draw_winrate: "33.97",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/steel",
    total_matches: "282",
    wins: "71",
    overall_winrate: "25.18",
    wins_on_play: "41",
    matches_on_play: "148",
    play_winrate: "27.70",
    wins_on_draw: "30",
    matches_on_draw: "134",
    draw_winrate: "22.39",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/sapphire",
    total_matches: "272",
    wins: "111",
    overall_winrate: "40.81",
    wins_on_play: "58",
    matches_on_play: "130",
    play_winrate: "44.62",
    wins_on_draw: "53",
    matches_on_draw: "142",
    draw_winrate: "37.32",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/emerald",
    total_matches: "228",
    wins: "66",
    overall_winrate: "28.95",
    wins_on_play: "40",
    matches_on_play: "126",
    play_winrate: "31.75",
    wins_on_draw: "26",
    matches_on_draw: "102",
    draw_winrate: "25.49",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/steel",
    total_matches: "194",
    wins: "43",
    overall_winrate: "22.16",
    wins_on_play: "20",
    matches_on_play: "90",
    play_winrate: "22.22",
    wins_on_draw: "23",
    matches_on_draw: "104",
    draw_winrate: "22.12",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "steel/emerald",
    total_matches: "157",
    wins: "63",
    overall_winrate: "40.13",
    wins_on_play: "35",
    matches_on_play: "78",
    play_winrate: "44.87",
    wins_on_draw: "28",
    matches_on_draw: "79",
    draw_winrate: "35.44",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "sapphire/steel",
    total_matches: "135",
    wins: "54",
    overall_winrate: "40.00",
    wins_on_play: "24",
    matches_on_play: "62",
    play_winrate: "38.71",
    wins_on_draw: "30",
    matches_on_draw: "73",
    draw_winrate: "41.10",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/sapphire",
    total_matches: "100",
    wins: "36",
    overall_winrate: "36.00",
    wins_on_play: "19",
    matches_on_play: "48",
    play_winrate: "39.58",
    wins_on_draw: "17",
    matches_on_draw: "52",
    draw_winrate: "32.69",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "sapphire/emerald",
    total_matches: "57",
    wins: "39",
    overall_winrate: "68.42",
    wins_on_play: "19",
    matches_on_play: "30",
    play_winrate: "63.33",
    wins_on_draw: "20",
    matches_on_draw: "27",
    draw_winrate: "74.07",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/ruby",
    total_matches: "52",
    wins: "21",
    overall_winrate: "40.38",
    wins_on_play: "13",
    matches_on_play: "30",
    play_winrate: "43.33",
    wins_on_draw: "8",
    matches_on_draw: "22",
    draw_winrate: "36.36",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/steel",
    total_matches: "45",
    wins: "19",
    overall_winrate: "42.22",
    wins_on_play: "11",
    matches_on_play: "25",
    play_winrate: "44.00",
    wins_on_draw: "8",
    matches_on_draw: "20",
    draw_winrate: "40.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/emerald",
    total_matches: "45",
    wins: "18",
    overall_winrate: "40.00",
    wins_on_play: "8",
    matches_on_play: "18",
    play_winrate: "44.44",
    wins_on_draw: "10",
    matches_on_draw: "27",
    draw_winrate: "37.04",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/emerald",
    total_matches: "40",
    wins: "40",
    overall_winrate: "100.00",
    wins_on_play: "36",
    matches_on_play: "36",
    play_winrate: "100.00",
    wins_on_draw: "34",
    matches_on_draw: "34",
    draw_winrate: "100.00",
    mirror_matches: "40",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/amethyst",
    total_matches: "35",
    wins: "16",
    overall_winrate: "45.71",
    wins_on_play: "11",
    matches_on_play: "20",
    play_winrate: "55.00",
    wins_on_draw: "5",
    matches_on_draw: "15",
    draw_winrate: "33.33",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/sapphire",
    total_matches: "21",
    wins: "6",
    overall_winrate: "28.57",
    wins_on_play: "3",
    matches_on_play: "8",
    play_winrate: "37.50",
    wins_on_draw: "3",
    matches_on_draw: "13",
    draw_winrate: "23.08",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/steel",
    total_matches: "954",
    wins: "263",
    overall_winrate: "27.57",
    wins_on_play: "164",
    matches_on_play: "479",
    play_winrate: "34.24",
    wins_on_draw: "99",
    matches_on_draw: "475",
    draw_winrate: "20.84",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/ruby",
    total_matches: "888",
    wins: "429",
    overall_winrate: "48.31",
    wins_on_play: "249",
    matches_on_play: "463",
    play_winrate: "53.78",
    wins_on_draw: "180",
    matches_on_draw: "425",
    draw_winrate: "42.35",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/sapphire",
    total_matches: "844",
    wins: "389",
    overall_winrate: "46.09",
    wins_on_play: "222",
    matches_on_play: "455",
    play_winrate: "48.79",
    wins_on_draw: "167",
    matches_on_draw: "389",
    draw_winrate: "42.93",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/emerald",
    total_matches: "690",
    wins: "203",
    overall_winrate: "29.42",
    wins_on_play: "118",
    matches_on_play: "343",
    play_winrate: "34.40",
    wins_on_draw: "85",
    matches_on_draw: "347",
    draw_winrate: "24.50",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/steel",
    total_matches: "643",
    wins: "221",
    overall_winrate: "34.37",
    wins_on_play: "127",
    matches_on_play: "315",
    play_winrate: "40.32",
    wins_on_draw: "94",
    matches_on_draw: "328",
    draw_winrate: "28.66",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "steel/emerald",
    total_matches: "420",
    wins: "119",
    overall_winrate: "28.33",
    wins_on_play: "68",
    matches_on_play: "207",
    play_winrate: "32.85",
    wins_on_draw: "51",
    matches_on_draw: "213",
    draw_winrate: "23.94",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "sapphire/steel",
    total_matches: "394",
    wins: "175",
    overall_winrate: "44.42",
    wins_on_play: "100",
    matches_on_play: "201",
    play_winrate: "49.75",
    wins_on_draw: "75",
    matches_on_draw: "193",
    draw_winrate: "38.86",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/sapphire",
    total_matches: "377",
    wins: "173",
    overall_winrate: "45.89",
    wins_on_play: "93",
    matches_on_play: "198",
    play_winrate: "46.97",
    wins_on_draw: "80",
    matches_on_draw: "179",
    draw_winrate: "44.69",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "sapphire/emerald",
    total_matches: "131",
    wins: "131",
    overall_winrate: "100.00",
    wins_on_play: "109",
    matches_on_play: "109",
    play_winrate: "100.00",
    wins_on_draw: "95",
    matches_on_draw: "95",
    draw_winrate: "100.00",
    mirror_matches: "131",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/ruby",
    total_matches: "116",
    wins: "49",
    overall_winrate: "42.24",
    wins_on_play: "30",
    matches_on_play: "62",
    play_winrate: "48.39",
    wins_on_draw: "19",
    matches_on_draw: "54",
    draw_winrate: "35.19",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/emerald",
    total_matches: "88",
    wins: "39",
    overall_winrate: "44.32",
    wins_on_play: "25",
    matches_on_play: "44",
    play_winrate: "56.82",
    wins_on_draw: "14",
    matches_on_draw: "44",
    draw_winrate: "31.82",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/amethyst",
    total_matches: "81",
    wins: "30",
    overall_winrate: "37.04",
    wins_on_play: "18",
    matches_on_play: "44",
    play_winrate: "40.91",
    wins_on_draw: "12",
    matches_on_draw: "37",
    draw_winrate: "32.43",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/emerald",
    total_matches: "57",
    wins: "18",
    overall_winrate: "31.58",
    wins_on_play: "7",
    matches_on_play: "27",
    play_winrate: "25.93",
    wins_on_draw: "11",
    matches_on_draw: "30",
    draw_winrate: "36.67",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/steel",
    total_matches: "57",
    wins: "19",
    overall_winrate: "33.33",
    wins_on_play: "16",
    matches_on_play: "37",
    play_winrate: "43.24",
    wins_on_draw: "3",
    matches_on_draw: "20",
    draw_winrate: "15.00",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/sapphire",
    total_matches: "41",
    wins: "20",
    overall_winrate: "48.78",
    wins_on_play: "14",
    matches_on_play: "22",
    play_winrate: "63.64",
    wins_on_draw: "6",
    matches_on_draw: "19",
    draw_winrate: "31.58",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/steel",
    total_matches: "3549",
    wins: "1658",
    overall_winrate: "46.72",
    wins_on_play: "937",
    matches_on_play: "1824",
    play_winrate: "51.37",
    wins_on_draw: "721",
    matches_on_draw: "1725",
    draw_winrate: "41.80",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/sapphire",
    total_matches: "3241",
    wins: "1301",
    overall_winrate: "40.14",
    wins_on_play: "684",
    matches_on_play: "1634",
    play_winrate: "41.86",
    wins_on_draw: "617",
    matches_on_draw: "1607",
    draw_winrate: "38.39",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/ruby",
    total_matches: "3227",
    wins: "1526",
    overall_winrate: "47.29",
    wins_on_play: "824",
    matches_on_play: "1627",
    play_winrate: "50.65",
    wins_on_draw: "702",
    matches_on_draw: "1600",
    draw_winrate: "43.88",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/emerald",
    total_matches: "2351",
    wins: "1261",
    overall_winrate: "53.64",
    wins_on_play: "727",
    matches_on_play: "1220",
    play_winrate: "59.59",
    wins_on_draw: "534",
    matches_on_draw: "1131",
    draw_winrate: "47.21",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/steel",
    total_matches: "2248",
    wins: "1079",
    overall_winrate: "48.00",
    wins_on_play: "562",
    matches_on_play: "1095",
    play_winrate: "51.32",
    wins_on_draw: "517",
    matches_on_draw: "1153",
    draw_winrate: "44.84",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "sapphire/steel",
    total_matches: "1412",
    wins: "653",
    overall_winrate: "46.25",
    wins_on_play: "360",
    matches_on_play: "736",
    play_winrate: "48.91",
    wins_on_draw: "293",
    matches_on_draw: "676",
    draw_winrate: "43.34",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/sapphire",
    total_matches: "1177",
    wins: "631",
    overall_winrate: "53.61",
    wins_on_play: "335",
    matches_on_play: "584",
    play_winrate: "57.36",
    wins_on_draw: "296",
    matches_on_draw: "593",
    draw_winrate: "49.92",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "steel/emerald",
    total_matches: "964",
    wins: "964",
    overall_winrate: "100.00",
    wins_on_play: "630",
    matches_on_play: "630",
    play_winrate: "100.00",
    wins_on_draw: "588",
    matches_on_draw: "588",
    draw_winrate: "100.00",
    mirror_matches: "964",
  },
  {
    deck: "steel/emerald",
    versus: "sapphire/emerald",
    total_matches: "420",
    wins: "301",
    overall_winrate: "71.67",
    wins_on_play: "162",
    matches_on_play: "213",
    play_winrate: "76.06",
    wins_on_draw: "139",
    matches_on_draw: "207",
    draw_winrate: "67.15",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/ruby",
    total_matches: "329",
    wins: "213",
    overall_winrate: "64.74",
    wins_on_play: "110",
    matches_on_play: "154",
    play_winrate: "71.43",
    wins_on_draw: "103",
    matches_on_draw: "175",
    draw_winrate: "58.86",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/emerald",
    total_matches: "322",
    wins: "214",
    overall_winrate: "66.46",
    wins_on_play: "119",
    matches_on_play: "171",
    play_winrate: "69.59",
    wins_on_draw: "95",
    matches_on_draw: "151",
    draw_winrate: "62.91",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/amethyst",
    total_matches: "282",
    wins: "201",
    overall_winrate: "71.28",
    wins_on_play: "115",
    matches_on_play: "146",
    play_winrate: "78.77",
    wins_on_draw: "86",
    matches_on_draw: "136",
    draw_winrate: "63.24",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/steel",
    total_matches: "204",
    wins: "131",
    overall_winrate: "64.22",
    wins_on_play: "64",
    matches_on_play: "94",
    play_winrate: "68.09",
    wins_on_draw: "67",
    matches_on_draw: "110",
    draw_winrate: "60.91",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/emerald",
    total_matches: "157",
    wins: "94",
    overall_winrate: "59.87",
    wins_on_play: "51",
    matches_on_play: "79",
    play_winrate: "64.56",
    wins_on_draw: "43",
    matches_on_draw: "78",
    draw_winrate: "55.13",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/sapphire",
    total_matches: "142",
    wins: "88",
    overall_winrate: "61.97",
    wins_on_play: "48",
    matches_on_play: "73",
    play_winrate: "65.75",
    wins_on_draw: "40",
    matches_on_draw: "69",
    draw_winrate: "57.97",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "steel",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/steel",
    total_matches: "7917",
    wins: "4658",
    overall_winrate: "58.84",
    wins_on_play: "2577",
    matches_on_play: "3890",
    play_winrate: "66.25",
    wins_on_draw: "2081",
    matches_on_draw: "4027",
    draw_winrate: "51.68",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/ruby",
    total_matches: "6779",
    wins: "3075",
    overall_winrate: "45.36",
    wins_on_play: "1788",
    matches_on_play: "3409",
    play_winrate: "52.45",
    wins_on_draw: "1287",
    matches_on_draw: "3370",
    draw_winrate: "38.19",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/emerald",
    total_matches: "5376",
    wins: "2062",
    overall_winrate: "38.36",
    wins_on_play: "1199",
    matches_on_play: "2634",
    play_winrate: "45.52",
    wins_on_draw: "863",
    matches_on_draw: "2742",
    draw_winrate: "31.47",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/steel",
    total_matches: "5079",
    wins: "2646",
    overall_winrate: "52.10",
    wins_on_play: "1512",
    matches_on_play: "2590",
    play_winrate: "58.38",
    wins_on_draw: "1134",
    matches_on_draw: "2489",
    draw_winrate: "45.56",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/sapphire",
    total_matches: "4310",
    wins: "4310",
    overall_winrate: "100.00",
    wins_on_play: "2479",
    matches_on_play: "2479",
    play_winrate: "100.00",
    wins_on_draw: "2333",
    matches_on_draw: "2333",
    draw_winrate: "100.00",
    mirror_matches: "4310",
  },
  {
    deck: "ruby/sapphire",
    versus: "steel/emerald",
    total_matches: "3241",
    wins: "1940",
    overall_winrate: "59.86",
    wins_on_play: "990",
    matches_on_play: "1607",
    play_winrate: "61.61",
    wins_on_draw: "950",
    matches_on_draw: "1634",
    draw_winrate: "58.14",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire/steel",
    total_matches: "2793",
    wins: "1726",
    overall_winrate: "61.80",
    wins_on_play: "911",
    matches_on_play: "1384",
    play_winrate: "65.82",
    wins_on_draw: "815",
    matches_on_draw: "1409",
    draw_winrate: "57.84",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "2700",
    wins: "1466",
    overall_winrate: "54.30",
    wins_on_play: "819",
    matches_on_play: "1344",
    play_winrate: "60.94",
    wins_on_draw: "647",
    matches_on_draw: "1356",
    draw_winrate: "47.71",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire/emerald",
    total_matches: "844",
    wins: "455",
    overall_winrate: "53.91",
    wins_on_play: "222",
    matches_on_play: "389",
    play_winrate: "57.07",
    wins_on_draw: "233",
    matches_on_draw: "455",
    draw_winrate: "51.21",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/emerald",
    total_matches: "668",
    wins: "308",
    overall_winrate: "46.11",
    wins_on_play: "175",
    matches_on_play: "334",
    play_winrate: "52.40",
    wins_on_draw: "133",
    matches_on_draw: "334",
    draw_winrate: "39.82",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/ruby",
    total_matches: "643",
    wins: "381",
    overall_winrate: "59.25",
    wins_on_play: "218",
    matches_on_play: "341",
    play_winrate: "63.93",
    wins_on_draw: "163",
    matches_on_draw: "302",
    draw_winrate: "53.97",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/amethyst",
    total_matches: "602",
    wins: "241",
    overall_winrate: "40.03",
    wins_on_play: "152",
    matches_on_play: "300",
    play_winrate: "50.67",
    wins_on_draw: "89",
    matches_on_draw: "302",
    draw_winrate: "29.47",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/steel",
    total_matches: "381",
    wins: "275",
    overall_winrate: "72.18",
    wins_on_play: "150",
    matches_on_play: "198",
    play_winrate: "75.76",
    wins_on_draw: "125",
    matches_on_draw: "183",
    draw_winrate: "68.31",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/sapphire",
    total_matches: "285",
    wins: "145",
    overall_winrate: "50.88",
    wins_on_play: "87",
    matches_on_play: "132",
    play_winrate: "65.91",
    wins_on_draw: "58",
    matches_on_draw: "153",
    draw_winrate: "37.91",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/emerald",
    total_matches: "272",
    wins: "161",
    overall_winrate: "59.19",
    wins_on_play: "89",
    matches_on_play: "142",
    play_winrate: "62.68",
    wins_on_draw: "72",
    matches_on_draw: "130",
    draw_winrate: "55.38",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst",
    total_matches: "2",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "1",
    play_winrate: "0.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: "0",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "steel",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: "0",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/steel",
    total_matches: "435",
    wins: "165",
    overall_winrate: "37.93",
    wins_on_play: "103",
    matches_on_play: "221",
    play_winrate: "46.61",
    wins_on_draw: "62",
    matches_on_draw: "214",
    draw_winrate: "28.97",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/ruby",
    total_matches: "428",
    wins: "136",
    overall_winrate: "31.78",
    wins_on_play: "73",
    matches_on_play: "201",
    play_winrate: "36.32",
    wins_on_draw: "63",
    matches_on_draw: "227",
    draw_winrate: "27.75",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/sapphire",
    total_matches: "381",
    wins: "106",
    overall_winrate: "27.82",
    wins_on_play: "58",
    matches_on_play: "183",
    play_winrate: "31.69",
    wins_on_draw: "48",
    matches_on_draw: "198",
    draw_winrate: "24.24",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/emerald",
    total_matches: "316",
    wins: "135",
    overall_winrate: "42.72",
    wins_on_play: "66",
    matches_on_play: "139",
    play_winrate: "47.48",
    wins_on_draw: "69",
    matches_on_draw: "177",
    draw_winrate: "38.98",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/steel",
    total_matches: "286",
    wins: "99",
    overall_winrate: "34.62",
    wins_on_play: "54",
    matches_on_play: "143",
    play_winrate: "37.76",
    wins_on_draw: "45",
    matches_on_draw: "143",
    draw_winrate: "31.47",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "steel/emerald",
    total_matches: "204",
    wins: "73",
    overall_winrate: "35.78",
    wins_on_play: "43",
    matches_on_play: "110",
    play_winrate: "39.09",
    wins_on_draw: "30",
    matches_on_draw: "94",
    draw_winrate: "31.91",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "sapphire/steel",
    total_matches: "174",
    wins: "72",
    overall_winrate: "41.38",
    wins_on_play: "35",
    matches_on_play: "85",
    play_winrate: "41.18",
    wins_on_draw: "37",
    matches_on_draw: "89",
    draw_winrate: "41.57",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/sapphire",
    total_matches: "135",
    wins: "39",
    overall_winrate: "28.89",
    wins_on_play: "22",
    matches_on_play: "69",
    play_winrate: "31.88",
    wins_on_draw: "17",
    matches_on_draw: "66",
    draw_winrate: "25.76",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/ruby",
    total_matches: "75",
    wins: "42",
    overall_winrate: "56.00",
    wins_on_play: "18",
    matches_on_play: "35",
    play_winrate: "51.43",
    wins_on_draw: "24",
    matches_on_draw: "40",
    draw_winrate: "60.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/steel",
    total_matches: "68",
    wins: "68",
    overall_winrate: "100.00",
    wins_on_play: "55",
    matches_on_play: "55",
    play_winrate: "100.00",
    wins_on_draw: "57",
    matches_on_draw: "57",
    draw_winrate: "100.00",
    mirror_matches: "68",
  },
  {
    deck: "ruby/steel",
    versus: "amber/amethyst",
    total_matches: "63",
    wins: "41",
    overall_winrate: "65.08",
    wins_on_play: "24",
    matches_on_play: "39",
    play_winrate: "61.54",
    wins_on_draw: "17",
    matches_on_draw: "24",
    draw_winrate: "70.83",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/emerald",
    total_matches: "59",
    wins: "30",
    overall_winrate: "50.85",
    wins_on_play: "15",
    matches_on_play: "30",
    play_winrate: "50.00",
    wins_on_draw: "15",
    matches_on_draw: "29",
    draw_winrate: "51.72",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "sapphire/emerald",
    total_matches: "57",
    wins: "38",
    overall_winrate: "66.67",
    wins_on_play: "17",
    matches_on_play: "20",
    play_winrate: "85.00",
    wins_on_draw: "21",
    matches_on_draw: "37",
    draw_winrate: "56.76",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/emerald",
    total_matches: "45",
    wins: "26",
    overall_winrate: "57.78",
    wins_on_play: "12",
    matches_on_play: "20",
    play_winrate: "60.00",
    wins_on_draw: "14",
    matches_on_draw: "25",
    draw_winrate: "56.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/sapphire",
    total_matches: "26",
    wins: "17",
    overall_winrate: "65.38",
    wins_on_play: "10",
    matches_on_play: "13",
    play_winrate: "76.92",
    wins_on_draw: "7",
    matches_on_draw: "13",
    draw_winrate: "53.85",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/steel",
    total_matches: "3208",
    wins: "1344",
    overall_winrate: "41.90",
    wins_on_play: "778",
    matches_on_play: "1617",
    play_winrate: "48.11",
    wins_on_draw: "566",
    matches_on_draw: "1591",
    draw_winrate: "35.58",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/ruby",
    total_matches: "2901",
    wins: "1240",
    overall_winrate: "42.74",
    wins_on_play: "701",
    matches_on_play: "1409",
    play_winrate: "49.75",
    wins_on_draw: "539",
    matches_on_draw: "1492",
    draw_winrate: "36.13",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/sapphire",
    total_matches: "2793",
    wins: "1067",
    overall_winrate: "38.20",
    wins_on_play: "594",
    matches_on_play: "1409",
    play_winrate: "42.16",
    wins_on_draw: "473",
    matches_on_draw: "1384",
    draw_winrate: "34.18",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/emerald",
    total_matches: "2187",
    wins: "1198",
    overall_winrate: "54.78",
    wins_on_play: "683",
    matches_on_play: "1102",
    play_winrate: "61.98",
    wins_on_draw: "515",
    matches_on_draw: "1085",
    draw_winrate: "47.47",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/steel",
    total_matches: "2067",
    wins: "1030",
    overall_winrate: "49.83",
    wins_on_play: "579",
    matches_on_play: "1018",
    play_winrate: "56.88",
    wins_on_draw: "451",
    matches_on_draw: "1049",
    draw_winrate: "42.99",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "steel/emerald",
    total_matches: "1412",
    wins: "759",
    overall_winrate: "53.75",
    wins_on_play: "383",
    matches_on_play: "676",
    play_winrate: "56.66",
    wins_on_draw: "376",
    matches_on_draw: "736",
    draw_winrate: "51.09",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/sapphire",
    total_matches: "1051",
    wins: "448",
    overall_winrate: "42.63",
    wins_on_play: "264",
    matches_on_play: "525",
    play_winrate: "50.29",
    wins_on_draw: "184",
    matches_on_draw: "526",
    draw_winrate: "34.98",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "sapphire/steel",
    total_matches: "776",
    wins: "776",
    overall_winrate: "100.00",
    wins_on_play: "512",
    matches_on_play: "512",
    play_winrate: "100.00",
    wins_on_draw: "470",
    matches_on_draw: "470",
    draw_winrate: "100.00",
    mirror_matches: "776",
  },
  {
    deck: "sapphire/steel",
    versus: "sapphire/emerald",
    total_matches: "394",
    wins: "219",
    overall_winrate: "55.58",
    wins_on_play: "118",
    matches_on_play: "193",
    play_winrate: "61.14",
    wins_on_draw: "101",
    matches_on_draw: "201",
    draw_winrate: "50.25",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/ruby",
    total_matches: "344",
    wins: "180",
    overall_winrate: "52.33",
    wins_on_play: "103",
    matches_on_play: "183",
    play_winrate: "56.28",
    wins_on_draw: "77",
    matches_on_draw: "161",
    draw_winrate: "47.83",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/emerald",
    total_matches: "282",
    wins: "153",
    overall_winrate: "54.26",
    wins_on_play: "83",
    matches_on_play: "139",
    play_winrate: "59.71",
    wins_on_draw: "70",
    matches_on_draw: "143",
    draw_winrate: "48.95",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/amethyst",
    total_matches: "264",
    wins: "125",
    overall_winrate: "47.35",
    wins_on_play: "74",
    matches_on_play: "135",
    play_winrate: "54.81",
    wins_on_draw: "51",
    matches_on_draw: "129",
    draw_winrate: "39.53",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/steel",
    total_matches: "174",
    wins: "102",
    overall_winrate: "58.62",
    wins_on_play: "52",
    matches_on_play: "89",
    play_winrate: "58.43",
    wins_on_draw: "50",
    matches_on_draw: "85",
    draw_winrate: "58.82",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/emerald",
    total_matches: "135",
    wins: "81",
    overall_winrate: "60.00",
    wins_on_play: "43",
    matches_on_play: "73",
    play_winrate: "58.90",
    wins_on_draw: "38",
    matches_on_draw: "62",
    draw_winrate: "61.29",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/sapphire",
    total_matches: "134",
    wins: "58",
    overall_winrate: "43.28",
    wins_on_play: "31",
    matches_on_play: "67",
    play_winrate: "46.27",
    wins_on_draw: "27",
    matches_on_draw: "67",
    draw_winrate: "40.30",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber",
    total_matches: "4",
    wins: "3",
    overall_winrate: "75.00",
    wins_on_play: "3",
    matches_on_play: "3",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
];

export default async function Meta() {
  // const matchups: MatchupData[] = await matchupPerformance();
  // console.log(JSON.stringify(matchups));
  // const serverStats = await getServerStats({ category: "ranked" });
  // console.log(JSON.stringify(serverStats));
  return <MetaPage data={matchups} />;
}
