import { type ValidParams } from "@/spaces/cards/cardFilterHelpers";
import { MetaPage } from "@/spaces/meta/MetaPage";
import { matchupPerformance } from "@/db/drizzle/meta";
import type { MatchupData } from "@/spaces/meta/types";

export const dynamicParams = false;
export const dynamic = "force-static";
export const fetchCache = "force-cache";

const matchups: MatchupData[] = [
  {
    deck: "amber/amethyst",
    versus: "amber/steel",
    total_matches: "665",
    wins: "167",
    overall_winrate: "25.11",
    wins_on_play: "98",
    matches_on_play: "333",
    play_winrate: "29.43",
    wins_on_draw: "69",
    matches_on_draw: "332",
    draw_winrate: "20.78",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/ruby",
    total_matches: "626",
    wins: "340",
    overall_winrate: "54.31",
    wins_on_play: "191",
    matches_on_play: "310",
    play_winrate: "61.61",
    wins_on_draw: "149",
    matches_on_draw: "316",
    draw_winrate: "47.15",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/sapphire",
    total_matches: "578",
    wins: "345",
    overall_winrate: "59.69",
    wins_on_play: "205",
    matches_on_play: "291",
    play_winrate: "70.45",
    wins_on_draw: "140",
    matches_on_draw: "287",
    draw_winrate: "48.78",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/emerald",
    total_matches: "437",
    wins: "196",
    overall_winrate: "44.85",
    wins_on_play: "119",
    matches_on_play: "228",
    play_winrate: "52.19",
    wins_on_draw: "77",
    matches_on_draw: "209",
    draw_winrate: "36.84",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/steel",
    total_matches: "430",
    wins: "162",
    overall_winrate: "37.67",
    wins_on_play: "103",
    matches_on_play: "226",
    play_winrate: "45.58",
    wins_on_draw: "59",
    matches_on_draw: "204",
    draw_winrate: "28.92",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "steel/emerald",
    total_matches: "273",
    wins: "80",
    overall_winrate: "29.30",
    wins_on_play: "49",
    matches_on_play: "132",
    play_winrate: "37.12",
    wins_on_draw: "31",
    matches_on_draw: "141",
    draw_winrate: "21.99",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "sapphire/steel",
    total_matches: "258",
    wins: "135",
    overall_winrate: "52.33",
    wins_on_play: "76",
    matches_on_play: "126",
    play_winrate: "60.32",
    wins_on_draw: "59",
    matches_on_draw: "132",
    draw_winrate: "44.70",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amethyst/sapphire",
    total_matches: "206",
    wins: "99",
    overall_winrate: "48.06",
    wins_on_play: "58",
    matches_on_play: "103",
    play_winrate: "56.31",
    wins_on_draw: "41",
    matches_on_draw: "103",
    draw_winrate: "39.81",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/ruby",
    total_matches: "87",
    wins: "48",
    overall_winrate: "55.17",
    wins_on_play: "24",
    matches_on_play: "43",
    play_winrate: "55.81",
    wins_on_draw: "24",
    matches_on_draw: "44",
    draw_winrate: "54.55",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/amethyst",
    total_matches: "86",
    wins: "86",
    overall_winrate: "100.00",
    wins_on_play: "74",
    matches_on_play: "74",
    play_winrate: "100.00",
    wins_on_draw: "71",
    matches_on_draw: "71",
    draw_winrate: "100.00",
    mirror_matches: "86",
  },
  {
    deck: "amber/amethyst",
    versus: "sapphire/emerald",
    total_matches: "80",
    wins: "50",
    overall_winrate: "62.50",
    wins_on_play: "25",
    matches_on_play: "37",
    play_winrate: "67.57",
    wins_on_draw: "25",
    matches_on_draw: "43",
    draw_winrate: "58.14",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/emerald",
    total_matches: "65",
    wins: "33",
    overall_winrate: "50.77",
    wins_on_play: "22",
    matches_on_play: "36",
    play_winrate: "61.11",
    wins_on_draw: "11",
    matches_on_draw: "29",
    draw_winrate: "37.93",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/steel",
    total_matches: "61",
    wins: "20",
    overall_winrate: "32.79",
    wins_on_play: "6",
    matches_on_play: "23",
    play_winrate: "26.09",
    wins_on_draw: "14",
    matches_on_draw: "38",
    draw_winrate: "36.84",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "ruby/emerald",
    total_matches: "35",
    wins: "19",
    overall_winrate: "54.29",
    wins_on_play: "10",
    matches_on_play: "15",
    play_winrate: "66.67",
    wins_on_draw: "9",
    matches_on_draw: "20",
    draw_winrate: "45.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/amethyst",
    versus: "amber/sapphire",
    total_matches: "31",
    wins: "16",
    overall_winrate: "51.61",
    wins_on_play: "8",
    matches_on_play: "14",
    play_winrate: "57.14",
    wins_on_draw: "8",
    matches_on_draw: "17",
    draw_winrate: "47.06",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/steel",
    total_matches: "719",
    wins: "234",
    overall_winrate: "32.55",
    wins_on_play: "134",
    matches_on_play: "346",
    play_winrate: "38.73",
    wins_on_draw: "100",
    matches_on_draw: "373",
    draw_winrate: "26.81",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/ruby",
    total_matches: "690",
    wins: "310",
    overall_winrate: "44.93",
    wins_on_play: "192",
    matches_on_play: "357",
    play_winrate: "53.78",
    wins_on_draw: "118",
    matches_on_draw: "333",
    draw_winrate: "35.44",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/sapphire",
    total_matches: "660",
    wins: "358",
    overall_winrate: "54.24",
    wins_on_play: "199",
    matches_on_play: "331",
    play_winrate: "60.12",
    wins_on_draw: "159",
    matches_on_draw: "329",
    draw_winrate: "48.33",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/emerald",
    total_matches: "491",
    wins: "204",
    overall_winrate: "41.55",
    wins_on_play: "136",
    matches_on_play: "267",
    play_winrate: "50.94",
    wins_on_draw: "68",
    matches_on_draw: "224",
    draw_winrate: "30.36",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/steel",
    total_matches: "464",
    wins: "172",
    overall_winrate: "37.07",
    wins_on_play: "92",
    matches_on_play: "232",
    play_winrate: "39.66",
    wins_on_draw: "80",
    matches_on_draw: "232",
    draw_winrate: "34.48",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "steel/emerald",
    total_matches: "318",
    wins: "107",
    overall_winrate: "33.65",
    wins_on_play: "55",
    matches_on_play: "148",
    play_winrate: "37.16",
    wins_on_draw: "52",
    matches_on_draw: "170",
    draw_winrate: "30.59",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "sapphire/steel",
    total_matches: "273",
    wins: "127",
    overall_winrate: "46.52",
    wins_on_play: "72",
    matches_on_play: "140",
    play_winrate: "51.43",
    wins_on_draw: "55",
    matches_on_draw: "133",
    draw_winrate: "41.35",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amethyst/sapphire",
    total_matches: "265",
    wins: "132",
    overall_winrate: "49.81",
    wins_on_play: "75",
    matches_on_play: "121",
    play_winrate: "61.98",
    wins_on_draw: "57",
    matches_on_draw: "144",
    draw_winrate: "39.58",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/emerald",
    total_matches: "97",
    wins: "97",
    overall_winrate: "100.00",
    wins_on_play: "87",
    matches_on_play: "87",
    play_winrate: "100.00",
    wins_on_draw: "72",
    matches_on_draw: "72",
    draw_winrate: "100.00",
    mirror_matches: "97",
  },
  {
    deck: "amber/emerald",
    versus: "sapphire/emerald",
    total_matches: "87",
    wins: "48",
    overall_winrate: "55.17",
    wins_on_play: "29",
    matches_on_play: "43",
    play_winrate: "67.44",
    wins_on_draw: "19",
    matches_on_draw: "44",
    draw_winrate: "43.18",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/ruby",
    total_matches: "82",
    wins: "46",
    overall_winrate: "56.10",
    wins_on_play: "25",
    matches_on_play: "38",
    play_winrate: "65.79",
    wins_on_draw: "21",
    matches_on_draw: "44",
    draw_winrate: "47.73",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/amethyst",
    total_matches: "65",
    wins: "32",
    overall_winrate: "49.23",
    wins_on_play: "18",
    matches_on_play: "29",
    play_winrate: "62.07",
    wins_on_draw: "14",
    matches_on_draw: "36",
    draw_winrate: "38.89",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/steel",
    total_matches: "59",
    wins: "29",
    overall_winrate: "49.15",
    wins_on_play: "14",
    matches_on_play: "29",
    play_winrate: "48.28",
    wins_on_draw: "15",
    matches_on_draw: "30",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "ruby/emerald",
    total_matches: "44",
    wins: "26",
    overall_winrate: "59.09",
    wins_on_play: "16",
    matches_on_play: "26",
    play_winrate: "61.54",
    wins_on_draw: "10",
    matches_on_draw: "18",
    draw_winrate: "55.56",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "amber/sapphire",
    total_matches: "29",
    wins: "18",
    overall_winrate: "62.07",
    wins_on_play: "8",
    matches_on_play: "14",
    play_winrate: "57.14",
    wins_on_draw: "10",
    matches_on_draw: "15",
    draw_winrate: "66.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/emerald",
    versus: "steel",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/ruby",
    total_matches: "764",
    wins: "306",
    overall_winrate: "40.05",
    wins_on_play: "160",
    matches_on_play: "382",
    play_winrate: "41.88",
    wins_on_draw: "146",
    matches_on_draw: "382",
    draw_winrate: "38.22",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/steel",
    total_matches: "761",
    wins: "227",
    overall_winrate: "29.83",
    wins_on_play: "129",
    matches_on_play: "367",
    play_winrate: "35.15",
    wins_on_draw: "98",
    matches_on_draw: "394",
    draw_winrate: "24.87",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/sapphire",
    total_matches: "626",
    wins: "256",
    overall_winrate: "40.89",
    wins_on_play: "136",
    matches_on_play: "294",
    play_winrate: "46.26",
    wins_on_draw: "120",
    matches_on_draw: "332",
    draw_winrate: "36.14",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/steel",
    total_matches: "531",
    wins: "207",
    overall_winrate: "38.98",
    wins_on_play: "117",
    matches_on_play: "278",
    play_winrate: "42.09",
    wins_on_draw: "90",
    matches_on_draw: "253",
    draw_winrate: "35.57",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/emerald",
    total_matches: "522",
    wins: "214",
    overall_winrate: "41.00",
    wins_on_play: "120",
    matches_on_play: "243",
    play_winrate: "49.38",
    wins_on_draw: "94",
    matches_on_draw: "279",
    draw_winrate: "33.69",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "sapphire/steel",
    total_matches: "332",
    wins: "157",
    overall_winrate: "47.29",
    wins_on_play: "79",
    matches_on_play: "155",
    play_winrate: "50.97",
    wins_on_draw: "78",
    matches_on_draw: "177",
    draw_winrate: "44.07",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "steel/emerald",
    total_matches: "319",
    wins: "110",
    overall_winrate: "34.48",
    wins_on_play: "68",
    matches_on_play: "169",
    play_winrate: "40.24",
    wins_on_draw: "42",
    matches_on_draw: "150",
    draw_winrate: "28.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amethyst/sapphire",
    total_matches: "232",
    wins: "77",
    overall_winrate: "33.19",
    wins_on_play: "37",
    matches_on_play: "103",
    play_winrate: "35.92",
    wins_on_draw: "40",
    matches_on_draw: "129",
    draw_winrate: "31.01",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "sapphire/emerald",
    total_matches: "114",
    wins: "67",
    overall_winrate: "58.77",
    wins_on_play: "35",
    matches_on_play: "54",
    play_winrate: "64.81",
    wins_on_draw: "32",
    matches_on_draw: "60",
    draw_winrate: "53.33",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/ruby",
    total_matches: "98",
    wins: "98",
    overall_winrate: "100.00",
    wins_on_play: "75",
    matches_on_play: "75",
    play_winrate: "100.00",
    wins_on_draw: "70",
    matches_on_draw: "70",
    draw_winrate: "100.00",
    mirror_matches: "98",
  },
  {
    deck: "amber/ruby",
    versus: "amber/amethyst",
    total_matches: "87",
    wins: "39",
    overall_winrate: "44.83",
    wins_on_play: "20",
    matches_on_play: "44",
    play_winrate: "45.45",
    wins_on_draw: "19",
    matches_on_draw: "43",
    draw_winrate: "44.19",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/emerald",
    total_matches: "82",
    wins: "36",
    overall_winrate: "43.90",
    wins_on_play: "23",
    matches_on_play: "44",
    play_winrate: "52.27",
    wins_on_draw: "13",
    matches_on_draw: "38",
    draw_winrate: "34.21",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/steel",
    total_matches: "74",
    wins: "33",
    overall_winrate: "44.59",
    wins_on_play: "16",
    matches_on_play: "39",
    play_winrate: "41.03",
    wins_on_draw: "17",
    matches_on_draw: "35",
    draw_winrate: "48.57",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "ruby/emerald",
    total_matches: "50",
    wins: "30",
    overall_winrate: "60.00",
    wins_on_play: "13",
    matches_on_play: "20",
    play_winrate: "65.00",
    wins_on_draw: "17",
    matches_on_draw: "30",
    draw_winrate: "56.67",
    mirror_matches: "0",
  },
  {
    deck: "amber/ruby",
    versus: "amber/sapphire",
    total_matches: "49",
    wins: "30",
    overall_winrate: "61.22",
    wins_on_play: "14",
    matches_on_play: "22",
    play_winrate: "63.64",
    wins_on_draw: "16",
    matches_on_draw: "27",
    draw_winrate: "59.26",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/steel",
    total_matches: "377",
    wins: "94",
    overall_winrate: "24.93",
    wins_on_play: "57",
    matches_on_play: "201",
    play_winrate: "28.36",
    wins_on_draw: "37",
    matches_on_draw: "176",
    draw_winrate: "21.02",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/ruby",
    total_matches: "311",
    wins: "121",
    overall_winrate: "38.91",
    wins_on_play: "71",
    matches_on_play: "155",
    play_winrate: "45.81",
    wins_on_draw: "50",
    matches_on_draw: "156",
    draw_winrate: "32.05",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/sapphire",
    total_matches: "280",
    wins: "139",
    overall_winrate: "49.64",
    wins_on_play: "94",
    matches_on_play: "151",
    play_winrate: "62.25",
    wins_on_draw: "45",
    matches_on_draw: "129",
    draw_winrate: "34.88",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/steel",
    total_matches: "248",
    wins: "84",
    overall_winrate: "33.87",
    wins_on_play: "44",
    matches_on_play: "116",
    play_winrate: "37.93",
    wins_on_draw: "40",
    matches_on_draw: "132",
    draw_winrate: "30.30",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/emerald",
    total_matches: "231",
    wins: "78",
    overall_winrate: "33.77",
    wins_on_play: "53",
    matches_on_play: "112",
    play_winrate: "47.32",
    wins_on_draw: "25",
    matches_on_draw: "119",
    draw_winrate: "21.01",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "steel/emerald",
    total_matches: "141",
    wins: "54",
    overall_winrate: "38.30",
    wins_on_play: "29",
    matches_on_play: "69",
    play_winrate: "42.03",
    wins_on_draw: "25",
    matches_on_draw: "72",
    draw_winrate: "34.72",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire/steel",
    total_matches: "132",
    wins: "75",
    overall_winrate: "56.82",
    wins_on_play: "39",
    matches_on_play: "66",
    play_winrate: "59.09",
    wins_on_draw: "36",
    matches_on_draw: "66",
    draw_winrate: "54.55",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "101",
    wins: "37",
    overall_winrate: "36.63",
    wins_on_play: "21",
    matches_on_play: "50",
    play_winrate: "42.00",
    wins_on_draw: "16",
    matches_on_draw: "51",
    draw_winrate: "31.37",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/ruby",
    total_matches: "49",
    wins: "19",
    overall_winrate: "38.78",
    wins_on_play: "11",
    matches_on_play: "27",
    play_winrate: "40.74",
    wins_on_draw: "8",
    matches_on_draw: "22",
    draw_winrate: "36.36",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire/emerald",
    total_matches: "41",
    wins: "21",
    overall_winrate: "51.22",
    wins_on_play: "13",
    matches_on_play: "19",
    play_winrate: "68.42",
    wins_on_draw: "8",
    matches_on_draw: "22",
    draw_winrate: "36.36",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/sapphire",
    total_matches: "33",
    wins: "33",
    overall_winrate: "100.00",
    wins_on_play: "31",
    matches_on_play: "31",
    play_winrate: "100.00",
    wins_on_draw: "26",
    matches_on_draw: "26",
    draw_winrate: "100.00",
    mirror_matches: "33",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/amethyst",
    total_matches: "31",
    wins: "15",
    overall_winrate: "48.39",
    wins_on_play: "9",
    matches_on_play: "17",
    play_winrate: "52.94",
    wins_on_draw: "6",
    matches_on_draw: "14",
    draw_winrate: "42.86",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "amber/emerald",
    total_matches: "29",
    wins: "11",
    overall_winrate: "37.93",
    wins_on_play: "5",
    matches_on_play: "15",
    play_winrate: "33.33",
    wins_on_draw: "6",
    matches_on_draw: "14",
    draw_winrate: "42.86",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/steel",
    total_matches: "26",
    wins: "9",
    overall_winrate: "34.62",
    wins_on_play: "6",
    matches_on_play: "13",
    play_winrate: "46.15",
    wins_on_draw: "3",
    matches_on_draw: "13",
    draw_winrate: "23.08",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "ruby/emerald",
    total_matches: "21",
    wins: "15",
    overall_winrate: "71.43",
    wins_on_play: "10",
    matches_on_play: "13",
    play_winrate: "76.92",
    wins_on_draw: "5",
    matches_on_draw: "8",
    draw_winrate: "62.50",
    mirror_matches: "0",
  },
  {
    deck: "amber/sapphire",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/sapphire",
    total_matches: "7745",
    wins: "3175",
    overall_winrate: "40.99",
    wins_on_play: "1895",
    matches_on_play: "3937",
    play_winrate: "48.13",
    wins_on_draw: "1280",
    matches_on_draw: "3808",
    draw_winrate: "33.61",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/ruby",
    total_matches: "7508",
    wins: "4166",
    overall_winrate: "55.49",
    wins_on_play: "2442",
    matches_on_play: "3835",
    play_winrate: "63.68",
    wins_on_draw: "1724",
    matches_on_draw: "3673",
    draw_winrate: "46.94",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/emerald",
    total_matches: "5877",
    wins: "3548",
    overall_winrate: "60.37",
    wins_on_play: "1956",
    matches_on_play: "2925",
    play_winrate: "66.87",
    wins_on_draw: "1592",
    matches_on_draw: "2952",
    draw_winrate: "53.93",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/steel",
    total_matches: "5427",
    wins: "2926",
    overall_winrate: "53.92",
    wins_on_play: "1601",
    matches_on_play: "2705",
    play_winrate: "59.19",
    wins_on_draw: "1325",
    matches_on_draw: "2722",
    draw_winrate: "48.68",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/steel",
    total_matches: "4880",
    wins: "4880",
    overall_winrate: "100.00",
    wins_on_play: "3009",
    matches_on_play: "3009",
    play_winrate: "100.00",
    wins_on_draw: "2388",
    matches_on_draw: "2388",
    draw_winrate: "100.00",
    mirror_matches: "4880",
  },
  {
    deck: "amber/steel",
    versus: "steel/emerald",
    total_matches: "3460",
    wins: "1846",
    overall_winrate: "53.35",
    wins_on_play: "977",
    matches_on_play: "1681",
    play_winrate: "58.12",
    wins_on_draw: "869",
    matches_on_draw: "1779",
    draw_winrate: "48.85",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire/steel",
    total_matches: "3106",
    wins: "1800",
    overall_winrate: "57.95",
    wins_on_play: "984",
    matches_on_play: "1536",
    play_winrate: "64.06",
    wins_on_draw: "816",
    matches_on_draw: "1570",
    draw_winrate: "51.97",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst/sapphire",
    total_matches: "2848",
    wins: "1612",
    overall_winrate: "56.60",
    wins_on_play: "878",
    matches_on_play: "1381",
    play_winrate: "63.58",
    wins_on_draw: "734",
    matches_on_draw: "1467",
    draw_winrate: "50.03",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire/emerald",
    total_matches: "936",
    wins: "681",
    overall_winrate: "72.76",
    wins_on_play: "368",
    matches_on_play: "464",
    play_winrate: "79.31",
    wins_on_draw: "313",
    matches_on_draw: "472",
    draw_winrate: "66.31",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/ruby",
    total_matches: "761",
    wins: "534",
    overall_winrate: "70.17",
    wins_on_play: "296",
    matches_on_play: "394",
    play_winrate: "75.13",
    wins_on_draw: "238",
    matches_on_draw: "367",
    draw_winrate: "64.85",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/emerald",
    total_matches: "719",
    wins: "485",
    overall_winrate: "67.45",
    wins_on_play: "273",
    matches_on_play: "373",
    play_winrate: "73.19",
    wins_on_draw: "212",
    matches_on_draw: "346",
    draw_winrate: "61.27",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/amethyst",
    total_matches: "665",
    wins: "498",
    overall_winrate: "74.89",
    wins_on_play: "263",
    matches_on_play: "332",
    play_winrate: "79.22",
    wins_on_draw: "235",
    matches_on_draw: "333",
    draw_winrate: "70.57",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/steel",
    total_matches: "425",
    wins: "265",
    overall_winrate: "62.35",
    wins_on_play: "150",
    matches_on_play: "209",
    play_winrate: "71.77",
    wins_on_draw: "115",
    matches_on_draw: "216",
    draw_winrate: "53.24",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber/sapphire",
    total_matches: "377",
    wins: "283",
    overall_winrate: "75.07",
    wins_on_play: "139",
    matches_on_play: "176",
    play_winrate: "78.98",
    wins_on_draw: "144",
    matches_on_draw: "201",
    draw_winrate: "71.64",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "ruby/emerald",
    total_matches: "275",
    wins: "206",
    overall_winrate: "74.91",
    wins_on_play: "103",
    matches_on_play: "133",
    play_winrate: "77.44",
    wins_on_draw: "103",
    matches_on_draw: "142",
    draw_winrate: "72.54",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amethyst",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "2",
    matches_on_play: "2",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "steel",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "2",
    draw_winrate: "50.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "amber",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amber/steel",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/steel",
    total_matches: "5877",
    wins: "2329",
    overall_winrate: "39.63",
    wins_on_play: "1360",
    matches_on_play: "2952",
    play_winrate: "46.07",
    wins_on_draw: "969",
    matches_on_draw: "2925",
    draw_winrate: "33.13",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/ruby",
    total_matches: "5321",
    wins: "3171",
    overall_winrate: "59.59",
    wins_on_play: "1799",
    matches_on_play: "2706",
    play_winrate: "66.48",
    wins_on_draw: "1372",
    matches_on_draw: "2615",
    draw_winrate: "52.47",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/sapphire",
    total_matches: "5247",
    wins: "3241",
    overall_winrate: "61.77",
    wins_on_play: "1829",
    matches_on_play: "2661",
    play_winrate: "68.73",
    wins_on_draw: "1412",
    matches_on_draw: "2586",
    draw_winrate: "54.60",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/steel",
    total_matches: "3745",
    wins: "1467",
    overall_winrate: "39.17",
    wins_on_play: "915",
    matches_on_play: "1937",
    play_winrate: "47.24",
    wins_on_draw: "552",
    matches_on_draw: "1808",
    draw_winrate: "30.53",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/emerald",
    total_matches: "2510",
    wins: "2510",
    overall_winrate: "100.00",
    wins_on_play: "1599",
    matches_on_play: "1599",
    play_winrate: "100.00",
    wins_on_draw: "1310",
    matches_on_draw: "1310",
    draw_winrate: "100.00",
    mirror_matches: "2510",
  },
  {
    deck: "amethyst/emerald",
    versus: "steel/emerald",
    total_matches: "2301",
    wins: "1069",
    overall_winrate: "46.46",
    wins_on_play: "585",
    matches_on_play: "1108",
    play_winrate: "52.80",
    wins_on_draw: "484",
    matches_on_draw: "1193",
    draw_winrate: "40.57",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire/steel",
    total_matches: "2126",
    wins: "963",
    overall_winrate: "45.30",
    wins_on_play: "553",
    matches_on_play: "1053",
    play_winrate: "52.52",
    wins_on_draw: "410",
    matches_on_draw: "1073",
    draw_winrate: "38.21",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst/sapphire",
    total_matches: "2018",
    wins: "1031",
    overall_winrate: "51.09",
    wins_on_play: "573",
    matches_on_play: "974",
    play_winrate: "58.83",
    wins_on_draw: "458",
    matches_on_draw: "1044",
    draw_winrate: "43.87",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire/emerald",
    total_matches: "677",
    wins: "479",
    overall_winrate: "70.75",
    wins_on_play: "259",
    matches_on_play: "341",
    play_winrate: "75.95",
    wins_on_draw: "220",
    matches_on_draw: "336",
    draw_winrate: "65.48",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/ruby",
    total_matches: "522",
    wins: "308",
    overall_winrate: "59.00",
    wins_on_play: "185",
    matches_on_play: "279",
    play_winrate: "66.31",
    wins_on_draw: "123",
    matches_on_draw: "243",
    draw_winrate: "50.62",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/emerald",
    total_matches: "491",
    wins: "287",
    overall_winrate: "58.45",
    wins_on_play: "156",
    matches_on_play: "224",
    play_winrate: "69.64",
    wins_on_draw: "131",
    matches_on_draw: "267",
    draw_winrate: "49.06",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/amethyst",
    total_matches: "437",
    wins: "241",
    overall_winrate: "55.15",
    wins_on_play: "132",
    matches_on_play: "209",
    play_winrate: "63.16",
    wins_on_draw: "109",
    matches_on_draw: "228",
    draw_winrate: "47.81",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/steel",
    total_matches: "311",
    wins: "179",
    overall_winrate: "57.56",
    wins_on_play: "107",
    matches_on_play: "174",
    play_winrate: "61.49",
    wins_on_draw: "72",
    matches_on_draw: "137",
    draw_winrate: "52.55",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber/sapphire",
    total_matches: "231",
    wins: "153",
    overall_winrate: "66.23",
    wins_on_play: "94",
    matches_on_play: "119",
    play_winrate: "78.99",
    wins_on_draw: "59",
    matches_on_draw: "112",
    draw_winrate: "52.68",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "ruby/emerald",
    total_matches: "225",
    wins: "159",
    overall_winrate: "70.67",
    wins_on_play: "74",
    matches_on_play: "100",
    play_winrate: "74.00",
    wins_on_draw: "85",
    matches_on_draw: "125",
    draw_winrate: "68.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "emerald",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amber",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "amethyst",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "sapphire",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/emerald",
    versus: "",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/steel",
    total_matches: "7508",
    wins: "3342",
    overall_winrate: "44.51",
    wins_on_play: "1949",
    matches_on_play: "3673",
    play_winrate: "53.06",
    wins_on_draw: "1393",
    matches_on_draw: "3835",
    draw_winrate: "36.32",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/sapphire",
    total_matches: "6614",
    wins: "3602",
    overall_winrate: "54.46",
    wins_on_play: "2027",
    matches_on_play: "3287",
    play_winrate: "61.67",
    wins_on_draw: "1575",
    matches_on_draw: "3327",
    draw_winrate: "47.34",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/emerald",
    total_matches: "5321",
    wins: "2150",
    overall_winrate: "40.41",
    wins_on_play: "1243",
    matches_on_play: "2615",
    play_winrate: "47.53",
    wins_on_draw: "907",
    matches_on_draw: "2706",
    draw_winrate: "33.52",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/steel",
    total_matches: "5086",
    wins: "2429",
    overall_winrate: "47.76",
    wins_on_play: "1403",
    matches_on_play: "2566",
    play_winrate: "54.68",
    wins_on_draw: "1026",
    matches_on_draw: "2520",
    draw_winrate: "40.71",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/ruby",
    total_matches: "4121",
    wins: "4121",
    overall_winrate: "100.00",
    wins_on_play: "2605",
    matches_on_play: "2605",
    play_winrate: "100.00",
    wins_on_draw: "2023",
    matches_on_draw: "2023",
    draw_winrate: "100.00",
    mirror_matches: "4121",
  },
  {
    deck: "amethyst/ruby",
    versus: "steel/emerald",
    total_matches: "3145",
    wins: "1660",
    overall_winrate: "52.78",
    wins_on_play: "877",
    matches_on_play: "1558",
    play_winrate: "56.29",
    wins_on_draw: "783",
    matches_on_draw: "1587",
    draw_winrate: "49.34",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire/steel",
    total_matches: "2801",
    wins: "1603",
    overall_winrate: "57.23",
    wins_on_play: "917",
    matches_on_play: "1442",
    play_winrate: "63.59",
    wins_on_draw: "686",
    matches_on_draw: "1359",
    draw_winrate: "50.48",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst/sapphire",
    total_matches: "2507",
    wins: "1249",
    overall_winrate: "49.82",
    wins_on_play: "745",
    matches_on_play: "1286",
    play_winrate: "57.93",
    wins_on_draw: "504",
    matches_on_draw: "1221",
    draw_winrate: "41.28",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire/emerald",
    total_matches: "872",
    wins: "451",
    overall_winrate: "51.72",
    wins_on_play: "241",
    matches_on_play: "419",
    play_winrate: "57.52",
    wins_on_draw: "210",
    matches_on_draw: "453",
    draw_winrate: "46.36",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/ruby",
    total_matches: "764",
    wins: "458",
    overall_winrate: "59.95",
    wins_on_play: "236",
    matches_on_play: "382",
    play_winrate: "61.78",
    wins_on_draw: "222",
    matches_on_draw: "382",
    draw_winrate: "58.12",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/emerald",
    total_matches: "690",
    wins: "380",
    overall_winrate: "55.07",
    wins_on_play: "215",
    matches_on_play: "333",
    play_winrate: "64.56",
    wins_on_draw: "165",
    matches_on_draw: "357",
    draw_winrate: "46.22",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/amethyst",
    total_matches: "626",
    wins: "286",
    overall_winrate: "45.69",
    wins_on_play: "167",
    matches_on_play: "316",
    play_winrate: "52.85",
    wins_on_draw: "119",
    matches_on_draw: "310",
    draw_winrate: "38.39",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/steel",
    total_matches: "423",
    wins: "288",
    overall_winrate: "68.09",
    wins_on_play: "161",
    matches_on_play: "223",
    play_winrate: "72.20",
    wins_on_draw: "127",
    matches_on_draw: "200",
    draw_winrate: "63.50",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber/sapphire",
    total_matches: "311",
    wins: "190",
    overall_winrate: "61.09",
    wins_on_play: "106",
    matches_on_play: "156",
    play_winrate: "67.95",
    wins_on_draw: "84",
    matches_on_draw: "155",
    draw_winrate: "54.19",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "ruby/emerald",
    total_matches: "300",
    wins: "182",
    overall_winrate: "60.67",
    wins_on_play: "101",
    matches_on_play: "153",
    play_winrate: "66.01",
    wins_on_draw: "81",
    matches_on_draw: "147",
    draw_winrate: "55.10",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "steel",
    total_matches: "2",
    wins: "1",
    overall_winrate: "50.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amber",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "amethyst",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/ruby",
    versus: "",
    total_matches: "1",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "1",
    play_winrate: "0.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/steel",
    total_matches: "2848",
    wins: "1236",
    overall_winrate: "43.40",
    wins_on_play: "733",
    matches_on_play: "1467",
    play_winrate: "49.97",
    wins_on_draw: "503",
    matches_on_draw: "1381",
    draw_winrate: "36.42",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/sapphire",
    total_matches: "2605",
    wins: "1183",
    overall_winrate: "45.41",
    wins_on_play: "675",
    matches_on_play: "1304",
    play_winrate: "51.76",
    wins_on_draw: "508",
    matches_on_draw: "1301",
    draw_winrate: "39.05",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/ruby",
    total_matches: "2507",
    wins: "1258",
    overall_winrate: "50.18",
    wins_on_play: "717",
    matches_on_play: "1221",
    play_winrate: "58.72",
    wins_on_draw: "541",
    matches_on_draw: "1286",
    draw_winrate: "42.07",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/emerald",
    total_matches: "2018",
    wins: "987",
    overall_winrate: "48.91",
    wins_on_play: "586",
    matches_on_play: "1044",
    play_winrate: "56.13",
    wins_on_draw: "401",
    matches_on_draw: "974",
    draw_winrate: "41.17",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/steel",
    total_matches: "1857",
    wins: "1010",
    overall_winrate: "54.39",
    wins_on_play: "571",
    matches_on_play: "911",
    play_winrate: "62.68",
    wins_on_draw: "439",
    matches_on_draw: "946",
    draw_winrate: "46.41",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "steel/emerald",
    total_matches: "1144",
    wins: "532",
    overall_winrate: "46.50",
    wins_on_play: "289",
    matches_on_play: "579",
    play_winrate: "49.91",
    wins_on_draw: "243",
    matches_on_draw: "565",
    draw_winrate: "43.01",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "sapphire/steel",
    total_matches: "1012",
    wins: "577",
    overall_winrate: "57.02",
    wins_on_play: "323",
    matches_on_play: "501",
    play_winrate: "64.47",
    wins_on_draw: "254",
    matches_on_draw: "511",
    draw_winrate: "49.71",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "604",
    wins: "604",
    overall_winrate: "100.00",
    wins_on_play: "409",
    matches_on_play: "409",
    play_winrate: "100.00",
    wins_on_draw: "345",
    matches_on_draw: "345",
    draw_winrate: "100.00",
    mirror_matches: "604",
  },
  {
    deck: "amethyst/sapphire",
    versus: "sapphire/emerald",
    total_matches: "371",
    wins: "202",
    overall_winrate: "54.45",
    wins_on_play: "98",
    matches_on_play: "175",
    play_winrate: "56.00",
    wins_on_draw: "104",
    matches_on_draw: "196",
    draw_winrate: "53.06",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/emerald",
    total_matches: "265",
    wins: "133",
    overall_winrate: "50.19",
    wins_on_play: "87",
    matches_on_play: "144",
    play_winrate: "60.42",
    wins_on_draw: "46",
    matches_on_draw: "121",
    draw_winrate: "38.02",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/ruby",
    total_matches: "232",
    wins: "155",
    overall_winrate: "66.81",
    wins_on_play: "89",
    matches_on_play: "129",
    play_winrate: "68.99",
    wins_on_draw: "66",
    matches_on_draw: "103",
    draw_winrate: "64.08",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/amethyst",
    total_matches: "206",
    wins: "107",
    overall_winrate: "51.94",
    wins_on_play: "62",
    matches_on_play: "103",
    play_winrate: "60.19",
    wins_on_draw: "45",
    matches_on_draw: "103",
    draw_winrate: "43.69",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/steel",
    total_matches: "133",
    wins: "94",
    overall_winrate: "70.68",
    wins_on_play: "48",
    matches_on_play: "65",
    play_winrate: "73.85",
    wins_on_draw: "46",
    matches_on_draw: "68",
    draw_winrate: "67.65",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amber/sapphire",
    total_matches: "101",
    wins: "64",
    overall_winrate: "63.37",
    wins_on_play: "35",
    matches_on_play: "51",
    play_winrate: "68.63",
    wins_on_draw: "29",
    matches_on_draw: "50",
    draw_winrate: "58.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "ruby/emerald",
    total_matches: "98",
    wins: "63",
    overall_winrate: "64.29",
    wins_on_play: "34",
    matches_on_play: "51",
    play_winrate: "66.67",
    wins_on_draw: "29",
    matches_on_draw: "47",
    draw_winrate: "61.70",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "amethyst",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "amethyst/sapphire",
    versus: "emerald",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/steel",
    total_matches: "5427",
    wins: "2501",
    overall_winrate: "46.08",
    wins_on_play: "1397",
    matches_on_play: "2722",
    play_winrate: "51.32",
    wins_on_draw: "1104",
    matches_on_draw: "2705",
    draw_winrate: "40.81",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/ruby",
    total_matches: "5086",
    wins: "2657",
    overall_winrate: "52.24",
    wins_on_play: "1494",
    matches_on_play: "2520",
    play_winrate: "59.29",
    wins_on_draw: "1163",
    matches_on_draw: "2566",
    draw_winrate: "45.32",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/sapphire",
    total_matches: "4940",
    wins: "2361",
    overall_winrate: "47.79",
    wins_on_play: "1313",
    matches_on_play: "2413",
    play_winrate: "54.41",
    wins_on_draw: "1048",
    matches_on_draw: "2527",
    draw_winrate: "41.47",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/emerald",
    total_matches: "3745",
    wins: "2278",
    overall_winrate: "60.83",
    wins_on_play: "1256",
    matches_on_play: "1808",
    play_winrate: "69.47",
    wins_on_draw: "1022",
    matches_on_draw: "1937",
    draw_winrate: "52.76",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/steel",
    total_matches: "2238",
    wins: "2238",
    overall_winrate: "100.00",
    wins_on_play: "1420",
    matches_on_play: "1420",
    play_winrate: "100.00",
    wins_on_draw: "1224",
    matches_on_draw: "1224",
    draw_winrate: "100.00",
    mirror_matches: "2238",
  },
  {
    deck: "amethyst/steel",
    versus: "steel/emerald",
    total_matches: "2192",
    wins: "1147",
    overall_winrate: "52.33",
    wins_on_play: "625",
    matches_on_play: "1124",
    play_winrate: "55.60",
    wins_on_draw: "522",
    matches_on_draw: "1068",
    draw_winrate: "48.88",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire/steel",
    total_matches: "2021",
    wins: "1017",
    overall_winrate: "50.32",
    wins_on_play: "584",
    matches_on_play: "1020",
    play_winrate: "57.25",
    wins_on_draw: "433",
    matches_on_draw: "1001",
    draw_winrate: "43.26",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst/sapphire",
    total_matches: "1857",
    wins: "847",
    overall_winrate: "45.61",
    wins_on_play: "507",
    matches_on_play: "946",
    play_winrate: "53.59",
    wins_on_draw: "340",
    matches_on_draw: "911",
    draw_winrate: "37.32",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "sapphire/emerald",
    total_matches: "633",
    wins: "418",
    overall_winrate: "66.03",
    wins_on_play: "231",
    matches_on_play: "322",
    play_winrate: "71.74",
    wins_on_draw: "187",
    matches_on_draw: "311",
    draw_winrate: "60.13",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/ruby",
    total_matches: "531",
    wins: "324",
    overall_winrate: "61.02",
    wins_on_play: "163",
    matches_on_play: "253",
    play_winrate: "64.43",
    wins_on_draw: "161",
    matches_on_draw: "278",
    draw_winrate: "57.91",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/emerald",
    total_matches: "464",
    wins: "292",
    overall_winrate: "62.93",
    wins_on_play: "152",
    matches_on_play: "232",
    play_winrate: "65.52",
    wins_on_draw: "140",
    matches_on_draw: "232",
    draw_winrate: "60.34",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/amethyst",
    total_matches: "430",
    wins: "268",
    overall_winrate: "62.33",
    wins_on_play: "145",
    matches_on_play: "204",
    play_winrate: "71.08",
    wins_on_draw: "123",
    matches_on_draw: "226",
    draw_winrate: "54.42",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/steel",
    total_matches: "283",
    wins: "186",
    overall_winrate: "65.72",
    wins_on_play: "98",
    matches_on_play: "143",
    play_winrate: "68.53",
    wins_on_draw: "88",
    matches_on_draw: "140",
    draw_winrate: "62.86",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amber/sapphire",
    total_matches: "248",
    wins: "164",
    overall_winrate: "66.13",
    wins_on_play: "92",
    matches_on_play: "132",
    play_winrate: "69.70",
    wins_on_draw: "72",
    matches_on_draw: "116",
    draw_winrate: "62.07",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "ruby/emerald",
    total_matches: "188",
    wins: "146",
    overall_winrate: "77.66",
    wins_on_play: "79",
    matches_on_play: "101",
    play_winrate: "78.22",
    wins_on_draw: "67",
    matches_on_draw: "87",
    draw_winrate: "77.01",
    mirror_matches: "0",
  },
  {
    deck: "amethyst/steel",
    versus: "amethyst",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/ruby",
    total_matches: "300",
    wins: "118",
    overall_winrate: "39.33",
    wins_on_play: "66",
    matches_on_play: "147",
    play_winrate: "44.90",
    wins_on_draw: "52",
    matches_on_draw: "153",
    draw_winrate: "33.99",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/steel",
    total_matches: "275",
    wins: "69",
    overall_winrate: "25.09",
    wins_on_play: "39",
    matches_on_play: "142",
    play_winrate: "27.46",
    wins_on_draw: "30",
    matches_on_draw: "133",
    draw_winrate: "22.56",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/sapphire",
    total_matches: "261",
    wins: "105",
    overall_winrate: "40.23",
    wins_on_play: "56",
    matches_on_play: "127",
    play_winrate: "44.09",
    wins_on_draw: "49",
    matches_on_draw: "134",
    draw_winrate: "36.57",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/emerald",
    total_matches: "225",
    wins: "66",
    overall_winrate: "29.33",
    wins_on_play: "40",
    matches_on_play: "125",
    play_winrate: "32.00",
    wins_on_draw: "26",
    matches_on_draw: "100",
    draw_winrate: "26.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/steel",
    total_matches: "188",
    wins: "42",
    overall_winrate: "22.34",
    wins_on_play: "20",
    matches_on_play: "87",
    play_winrate: "22.99",
    wins_on_draw: "22",
    matches_on_draw: "101",
    draw_winrate: "21.78",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "steel/emerald",
    total_matches: "157",
    wins: "63",
    overall_winrate: "40.13",
    wins_on_play: "35",
    matches_on_play: "78",
    play_winrate: "44.87",
    wins_on_draw: "28",
    matches_on_draw: "79",
    draw_winrate: "35.44",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "sapphire/steel",
    total_matches: "131",
    wins: "52",
    overall_winrate: "39.69",
    wins_on_play: "23",
    matches_on_play: "61",
    play_winrate: "37.70",
    wins_on_draw: "29",
    matches_on_draw: "70",
    draw_winrate: "41.43",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amethyst/sapphire",
    total_matches: "98",
    wins: "35",
    overall_winrate: "35.71",
    wins_on_play: "18",
    matches_on_play: "47",
    play_winrate: "38.30",
    wins_on_draw: "17",
    matches_on_draw: "51",
    draw_winrate: "33.33",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "sapphire/emerald",
    total_matches: "57",
    wins: "39",
    overall_winrate: "68.42",
    wins_on_play: "19",
    matches_on_play: "30",
    play_winrate: "63.33",
    wins_on_draw: "20",
    matches_on_draw: "27",
    draw_winrate: "74.07",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/ruby",
    total_matches: "50",
    wins: "20",
    overall_winrate: "40.00",
    wins_on_play: "13",
    matches_on_play: "30",
    play_winrate: "43.33",
    wins_on_draw: "7",
    matches_on_draw: "20",
    draw_winrate: "35.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/steel",
    total_matches: "44",
    wins: "19",
    overall_winrate: "43.18",
    wins_on_play: "11",
    matches_on_play: "24",
    play_winrate: "45.83",
    wins_on_draw: "8",
    matches_on_draw: "20",
    draw_winrate: "40.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/emerald",
    total_matches: "44",
    wins: "18",
    overall_winrate: "40.91",
    wins_on_play: "8",
    matches_on_play: "18",
    play_winrate: "44.44",
    wins_on_draw: "10",
    matches_on_draw: "26",
    draw_winrate: "38.46",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "ruby/emerald",
    total_matches: "40",
    wins: "40",
    overall_winrate: "100.00",
    wins_on_play: "36",
    matches_on_play: "36",
    play_winrate: "100.00",
    wins_on_draw: "34",
    matches_on_draw: "34",
    draw_winrate: "100.00",
    mirror_matches: "40",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/amethyst",
    total_matches: "35",
    wins: "16",
    overall_winrate: "45.71",
    wins_on_play: "11",
    matches_on_play: "20",
    play_winrate: "55.00",
    wins_on_draw: "5",
    matches_on_draw: "15",
    draw_winrate: "33.33",
    mirror_matches: "0",
  },
  {
    deck: "ruby/emerald",
    versus: "amber/sapphire",
    total_matches: "21",
    wins: "6",
    overall_winrate: "28.57",
    wins_on_play: "3",
    matches_on_play: "8",
    play_winrate: "37.50",
    wins_on_draw: "3",
    matches_on_draw: "13",
    draw_winrate: "23.08",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/steel",
    total_matches: "936",
    wins: "255",
    overall_winrate: "27.24",
    wins_on_play: "159",
    matches_on_play: "472",
    play_winrate: "33.69",
    wins_on_draw: "96",
    matches_on_draw: "464",
    draw_winrate: "20.69",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/ruby",
    total_matches: "872",
    wins: "421",
    overall_winrate: "48.28",
    wins_on_play: "243",
    matches_on_play: "453",
    play_winrate: "53.64",
    wins_on_draw: "178",
    matches_on_draw: "419",
    draw_winrate: "42.48",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/sapphire",
    total_matches: "833",
    wins: "382",
    overall_winrate: "45.86",
    wins_on_play: "220",
    matches_on_play: "451",
    play_winrate: "48.78",
    wins_on_draw: "162",
    matches_on_draw: "382",
    draw_winrate: "42.41",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/emerald",
    total_matches: "677",
    wins: "198",
    overall_winrate: "29.25",
    wins_on_play: "116",
    matches_on_play: "336",
    play_winrate: "34.52",
    wins_on_draw: "82",
    matches_on_draw: "341",
    draw_winrate: "24.05",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/steel",
    total_matches: "633",
    wins: "215",
    overall_winrate: "33.97",
    wins_on_play: "124",
    matches_on_play: "311",
    play_winrate: "39.87",
    wins_on_draw: "91",
    matches_on_draw: "322",
    draw_winrate: "28.26",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "steel/emerald",
    total_matches: "416",
    wins: "118",
    overall_winrate: "28.37",
    wins_on_play: "67",
    matches_on_play: "204",
    play_winrate: "32.84",
    wins_on_draw: "51",
    matches_on_draw: "212",
    draw_winrate: "24.06",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "sapphire/steel",
    total_matches: "383",
    wins: "170",
    overall_winrate: "44.39",
    wins_on_play: "98",
    matches_on_play: "198",
    play_winrate: "49.49",
    wins_on_draw: "72",
    matches_on_draw: "185",
    draw_winrate: "38.92",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amethyst/sapphire",
    total_matches: "371",
    wins: "169",
    overall_winrate: "45.55",
    wins_on_play: "92",
    matches_on_play: "196",
    play_winrate: "46.94",
    wins_on_draw: "77",
    matches_on_draw: "175",
    draw_winrate: "44.00",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "sapphire/emerald",
    total_matches: "131",
    wins: "131",
    overall_winrate: "100.00",
    wins_on_play: "109",
    matches_on_play: "109",
    play_winrate: "100.00",
    wins_on_draw: "95",
    matches_on_draw: "95",
    draw_winrate: "100.00",
    mirror_matches: "131",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/ruby",
    total_matches: "114",
    wins: "47",
    overall_winrate: "41.23",
    wins_on_play: "28",
    matches_on_play: "60",
    play_winrate: "46.67",
    wins_on_draw: "19",
    matches_on_draw: "54",
    draw_winrate: "35.19",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/emerald",
    total_matches: "87",
    wins: "39",
    overall_winrate: "44.83",
    wins_on_play: "25",
    matches_on_play: "44",
    play_winrate: "56.82",
    wins_on_draw: "14",
    matches_on_draw: "43",
    draw_winrate: "32.56",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/amethyst",
    total_matches: "80",
    wins: "30",
    overall_winrate: "37.50",
    wins_on_play: "18",
    matches_on_play: "43",
    play_winrate: "41.86",
    wins_on_draw: "12",
    matches_on_draw: "37",
    draw_winrate: "32.43",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/emerald",
    total_matches: "57",
    wins: "18",
    overall_winrate: "31.58",
    wins_on_play: "7",
    matches_on_play: "27",
    play_winrate: "25.93",
    wins_on_draw: "11",
    matches_on_draw: "30",
    draw_winrate: "36.67",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "ruby/steel",
    total_matches: "56",
    wins: "19",
    overall_winrate: "33.93",
    wins_on_play: "16",
    matches_on_play: "36",
    play_winrate: "44.44",
    wins_on_draw: "3",
    matches_on_draw: "20",
    draw_winrate: "15.00",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/emerald",
    versus: "amber/sapphire",
    total_matches: "41",
    wins: "20",
    overall_winrate: "48.78",
    wins_on_play: "14",
    matches_on_play: "22",
    play_winrate: "63.64",
    wins_on_draw: "6",
    matches_on_draw: "19",
    draw_winrate: "31.58",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/steel",
    total_matches: "3460",
    wins: "1614",
    overall_winrate: "46.65",
    wins_on_play: "910",
    matches_on_play: "1779",
    play_winrate: "51.15",
    wins_on_draw: "704",
    matches_on_draw: "1681",
    draw_winrate: "41.88",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/sapphire",
    total_matches: "3146",
    wins: "1269",
    overall_winrate: "40.34",
    wins_on_play: "667",
    matches_on_play: "1585",
    play_winrate: "42.08",
    wins_on_draw: "602",
    matches_on_draw: "1561",
    draw_winrate: "38.57",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/ruby",
    total_matches: "3145",
    wins: "1485",
    overall_winrate: "47.22",
    wins_on_play: "804",
    matches_on_play: "1587",
    play_winrate: "50.66",
    wins_on_draw: "681",
    matches_on_draw: "1558",
    draw_winrate: "43.71",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/emerald",
    total_matches: "2301",
    wins: "1232",
    overall_winrate: "53.54",
    wins_on_play: "709",
    matches_on_play: "1193",
    play_winrate: "59.43",
    wins_on_draw: "523",
    matches_on_draw: "1108",
    draw_winrate: "47.20",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/steel",
    total_matches: "2192",
    wins: "1045",
    overall_winrate: "47.67",
    wins_on_play: "546",
    matches_on_play: "1068",
    play_winrate: "51.12",
    wins_on_draw: "499",
    matches_on_draw: "1124",
    draw_winrate: "44.40",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "sapphire/steel",
    total_matches: "1362",
    wins: "636",
    overall_winrate: "46.70",
    wins_on_play: "353",
    matches_on_play: "718",
    play_winrate: "49.16",
    wins_on_draw: "283",
    matches_on_draw: "644",
    draw_winrate: "43.94",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amethyst/sapphire",
    total_matches: "1144",
    wins: "612",
    overall_winrate: "53.50",
    wins_on_play: "322",
    matches_on_play: "565",
    play_winrate: "56.99",
    wins_on_draw: "290",
    matches_on_draw: "579",
    draw_winrate: "50.09",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "steel/emerald",
    total_matches: "938",
    wins: "938",
    overall_winrate: "100.00",
    wins_on_play: "614",
    matches_on_play: "614",
    play_winrate: "100.00",
    wins_on_draw: "571",
    matches_on_draw: "571",
    draw_winrate: "100.00",
    mirror_matches: "938",
  },
  {
    deck: "steel/emerald",
    versus: "sapphire/emerald",
    total_matches: "416",
    wins: "298",
    overall_winrate: "71.63",
    wins_on_play: "161",
    matches_on_play: "212",
    play_winrate: "75.94",
    wins_on_draw: "137",
    matches_on_draw: "204",
    draw_winrate: "67.16",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/ruby",
    total_matches: "319",
    wins: "209",
    overall_winrate: "65.52",
    wins_on_play: "108",
    matches_on_play: "150",
    play_winrate: "72.00",
    wins_on_draw: "101",
    matches_on_draw: "169",
    draw_winrate: "59.76",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/emerald",
    total_matches: "318",
    wins: "211",
    overall_winrate: "66.35",
    wins_on_play: "118",
    matches_on_play: "170",
    play_winrate: "69.41",
    wins_on_draw: "93",
    matches_on_draw: "148",
    draw_winrate: "62.84",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/amethyst",
    total_matches: "273",
    wins: "193",
    overall_winrate: "70.70",
    wins_on_play: "110",
    matches_on_play: "141",
    play_winrate: "78.01",
    wins_on_draw: "83",
    matches_on_draw: "132",
    draw_winrate: "62.88",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/steel",
    total_matches: "199",
    wins: "128",
    overall_winrate: "64.32",
    wins_on_play: "63",
    matches_on_play: "91",
    play_winrate: "69.23",
    wins_on_draw: "65",
    matches_on_draw: "108",
    draw_winrate: "60.19",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "ruby/emerald",
    total_matches: "157",
    wins: "94",
    overall_winrate: "59.87",
    wins_on_play: "51",
    matches_on_play: "79",
    play_winrate: "64.56",
    wins_on_draw: "43",
    matches_on_draw: "78",
    draw_winrate: "55.13",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber/sapphire",
    total_matches: "141",
    wins: "87",
    overall_winrate: "61.70",
    wins_on_play: "47",
    matches_on_play: "72",
    play_winrate: "65.28",
    wins_on_draw: "40",
    matches_on_draw: "69",
    draw_winrate: "57.97",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "amber",
    total_matches: "2",
    wins: "2",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "steel/emerald",
    versus: "steel",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/steel",
    total_matches: "7745",
    wins: "4570",
    overall_winrate: "59.01",
    wins_on_play: "2528",
    matches_on_play: "3808",
    play_winrate: "66.39",
    wins_on_draw: "2042",
    matches_on_draw: "3937",
    draw_winrate: "51.87",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/ruby",
    total_matches: "6614",
    wins: "3012",
    overall_winrate: "45.54",
    wins_on_play: "1752",
    matches_on_play: "3327",
    play_winrate: "52.66",
    wins_on_draw: "1260",
    matches_on_draw: "3287",
    draw_winrate: "38.33",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/emerald",
    total_matches: "5247",
    wins: "2006",
    overall_winrate: "38.23",
    wins_on_play: "1174",
    matches_on_play: "2586",
    play_winrate: "45.40",
    wins_on_draw: "832",
    matches_on_draw: "2661",
    draw_winrate: "31.27",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/steel",
    total_matches: "4940",
    wins: "2579",
    overall_winrate: "52.21",
    wins_on_play: "1479",
    matches_on_play: "2527",
    play_winrate: "58.53",
    wins_on_draw: "1100",
    matches_on_draw: "2413",
    draw_winrate: "45.59",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/sapphire",
    total_matches: "4191",
    wins: "4191",
    overall_winrate: "100.00",
    wins_on_play: "2414",
    matches_on_play: "2414",
    play_winrate: "100.00",
    wins_on_draw: "2261",
    matches_on_draw: "2261",
    draw_winrate: "100.00",
    mirror_matches: "4191",
  },
  {
    deck: "ruby/sapphire",
    versus: "steel/emerald",
    total_matches: "3146",
    wins: "1877",
    overall_winrate: "59.66",
    wins_on_play: "959",
    matches_on_play: "1561",
    play_winrate: "61.43",
    wins_on_draw: "918",
    matches_on_draw: "1585",
    draw_winrate: "57.92",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire/steel",
    total_matches: "2717",
    wins: "1676",
    overall_winrate: "61.69",
    wins_on_play: "881",
    matches_on_play: "1340",
    play_winrate: "65.75",
    wins_on_draw: "795",
    matches_on_draw: "1377",
    draw_winrate: "57.73",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst/sapphire",
    total_matches: "2605",
    wins: "1422",
    overall_winrate: "54.59",
    wins_on_play: "793",
    matches_on_play: "1301",
    play_winrate: "60.95",
    wins_on_draw: "629",
    matches_on_draw: "1304",
    draw_winrate: "48.24",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire/emerald",
    total_matches: "833",
    wins: "451",
    overall_winrate: "54.14",
    wins_on_play: "220",
    matches_on_play: "382",
    play_winrate: "57.59",
    wins_on_draw: "231",
    matches_on_draw: "451",
    draw_winrate: "51.22",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/emerald",
    total_matches: "660",
    wins: "302",
    overall_winrate: "45.76",
    wins_on_play: "170",
    matches_on_play: "329",
    play_winrate: "51.67",
    wins_on_draw: "132",
    matches_on_draw: "331",
    draw_winrate: "39.88",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/ruby",
    total_matches: "626",
    wins: "370",
    overall_winrate: "59.11",
    wins_on_play: "212",
    matches_on_play: "332",
    play_winrate: "63.86",
    wins_on_draw: "158",
    matches_on_draw: "294",
    draw_winrate: "53.74",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/amethyst",
    total_matches: "578",
    wins: "233",
    overall_winrate: "40.31",
    wins_on_play: "147",
    matches_on_play: "287",
    play_winrate: "51.22",
    wins_on_draw: "86",
    matches_on_draw: "291",
    draw_winrate: "29.55",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/steel",
    total_matches: "379",
    wins: "274",
    overall_winrate: "72.30",
    wins_on_play: "150",
    matches_on_play: "197",
    play_winrate: "76.14",
    wins_on_draw: "124",
    matches_on_draw: "182",
    draw_winrate: "68.13",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amber/sapphire",
    total_matches: "280",
    wins: "141",
    overall_winrate: "50.36",
    wins_on_play: "84",
    matches_on_play: "129",
    play_winrate: "65.12",
    wins_on_draw: "57",
    matches_on_draw: "151",
    draw_winrate: "37.75",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "ruby/emerald",
    total_matches: "261",
    wins: "156",
    overall_winrate: "59.77",
    wins_on_play: "85",
    matches_on_play: "134",
    play_winrate: "63.43",
    wins_on_draw: "71",
    matches_on_draw: "127",
    draw_winrate: "55.91",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "amethyst",
    total_matches: "2",
    wins: "0",
    overall_winrate: "0.00",
    wins_on_play: "0",
    matches_on_play: "1",
    play_winrate: "0.00",
    wins_on_draw: "0",
    matches_on_draw: "1",
    draw_winrate: "0.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "sapphire",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "1",
    matches_on_play: "1",
    play_winrate: "100.00",
    wins_on_draw: "0",
    matches_on_draw: "0",
    draw_winrate: null,
    mirror_matches: "0",
  },
  {
    deck: "ruby/sapphire",
    versus: "steel",
    total_matches: "1",
    wins: "1",
    overall_winrate: "100.00",
    wins_on_play: "0",
    matches_on_play: "0",
    play_winrate: null,
    wins_on_draw: "1",
    matches_on_draw: "1",
    draw_winrate: "100.00",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/steel",
    total_matches: "425",
    wins: "160",
    overall_winrate: "37.65",
    wins_on_play: "101",
    matches_on_play: "216",
    play_winrate: "46.76",
    wins_on_draw: "59",
    matches_on_draw: "209",
    draw_winrate: "28.23",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/ruby",
    total_matches: "423",
    wins: "135",
    overall_winrate: "31.91",
    wins_on_play: "73",
    matches_on_play: "200",
    play_winrate: "36.50",
    wins_on_draw: "62",
    matches_on_draw: "223",
    draw_winrate: "27.80",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/sapphire",
    total_matches: "379",
    wins: "105",
    overall_winrate: "27.70",
    wins_on_play: "58",
    matches_on_play: "182",
    play_winrate: "31.87",
    wins_on_draw: "47",
    matches_on_draw: "197",
    draw_winrate: "23.86",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/emerald",
    total_matches: "311",
    wins: "132",
    overall_winrate: "42.44",
    wins_on_play: "65",
    matches_on_play: "137",
    play_winrate: "47.45",
    wins_on_draw: "67",
    matches_on_draw: "174",
    draw_winrate: "38.51",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/steel",
    total_matches: "283",
    wins: "97",
    overall_winrate: "34.28",
    wins_on_play: "52",
    matches_on_play: "140",
    play_winrate: "37.14",
    wins_on_draw: "45",
    matches_on_draw: "143",
    draw_winrate: "31.47",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "steel/emerald",
    total_matches: "199",
    wins: "71",
    overall_winrate: "35.68",
    wins_on_play: "43",
    matches_on_play: "108",
    play_winrate: "39.81",
    wins_on_draw: "28",
    matches_on_draw: "91",
    draw_winrate: "30.77",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "sapphire/steel",
    total_matches: "173",
    wins: "71",
    overall_winrate: "41.04",
    wins_on_play: "34",
    matches_on_play: "84",
    play_winrate: "40.48",
    wins_on_draw: "37",
    matches_on_draw: "89",
    draw_winrate: "41.57",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amethyst/sapphire",
    total_matches: "133",
    wins: "39",
    overall_winrate: "29.32",
    wins_on_play: "22",
    matches_on_play: "68",
    play_winrate: "32.35",
    wins_on_draw: "17",
    matches_on_draw: "65",
    draw_winrate: "26.15",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/ruby",
    total_matches: "74",
    wins: "41",
    overall_winrate: "55.41",
    wins_on_play: "18",
    matches_on_play: "35",
    play_winrate: "51.43",
    wins_on_draw: "23",
    matches_on_draw: "39",
    draw_winrate: "58.97",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/steel",
    total_matches: "66",
    wins: "66",
    overall_winrate: "100.00",
    wins_on_play: "53",
    matches_on_play: "53",
    play_winrate: "100.00",
    wins_on_draw: "55",
    matches_on_draw: "55",
    draw_winrate: "100.00",
    mirror_matches: "66",
  },
  {
    deck: "ruby/steel",
    versus: "amber/amethyst",
    total_matches: "61",
    wins: "41",
    overall_winrate: "67.21",
    wins_on_play: "24",
    matches_on_play: "38",
    play_winrate: "63.16",
    wins_on_draw: "17",
    matches_on_draw: "23",
    draw_winrate: "73.91",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/emerald",
    total_matches: "59",
    wins: "30",
    overall_winrate: "50.85",
    wins_on_play: "15",
    matches_on_play: "30",
    play_winrate: "50.00",
    wins_on_draw: "15",
    matches_on_draw: "29",
    draw_winrate: "51.72",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "sapphire/emerald",
    total_matches: "56",
    wins: "37",
    overall_winrate: "66.07",
    wins_on_play: "17",
    matches_on_play: "20",
    play_winrate: "85.00",
    wins_on_draw: "20",
    matches_on_draw: "36",
    draw_winrate: "55.56",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "ruby/emerald",
    total_matches: "44",
    wins: "25",
    overall_winrate: "56.82",
    wins_on_play: "12",
    matches_on_play: "20",
    play_winrate: "60.00",
    wins_on_draw: "13",
    matches_on_draw: "24",
    draw_winrate: "54.17",
    mirror_matches: "0",
  },
  {
    deck: "ruby/steel",
    versus: "amber/sapphire",
    total_matches: "26",
    wins: "17",
    overall_winrate: "65.38",
    wins_on_play: "10",
    matches_on_play: "13",
    play_winrate: "76.92",
    wins_on_draw: "7",
    matches_on_draw: "13",
    draw_winrate: "53.85",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/steel",
    total_matches: "3106",
    wins: "1306",
    overall_winrate: "42.05",
    wins_on_play: "754",
    matches_on_play: "1570",
    play_winrate: "48.03",
    wins_on_draw: "552",
    matches_on_draw: "1536",
    draw_winrate: "35.94",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/ruby",
    total_matches: "2801",
    wins: "1198",
    overall_winrate: "42.77",
    wins_on_play: "673",
    matches_on_play: "1359",
    play_winrate: "49.52",
    wins_on_draw: "525",
    matches_on_draw: "1442",
    draw_winrate: "36.41",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/sapphire",
    total_matches: "2717",
    wins: "1041",
    overall_winrate: "38.31",
    wins_on_play: "582",
    matches_on_play: "1377",
    play_winrate: "42.27",
    wins_on_draw: "459",
    matches_on_draw: "1340",
    draw_winrate: "34.25",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/emerald",
    total_matches: "2126",
    wins: "1163",
    overall_winrate: "54.70",
    wins_on_play: "663",
    matches_on_play: "1073",
    play_winrate: "61.79",
    wins_on_draw: "500",
    matches_on_draw: "1053",
    draw_winrate: "47.48",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/steel",
    total_matches: "2021",
    wins: "1004",
    overall_winrate: "49.68",
    wins_on_play: "568",
    matches_on_play: "1001",
    play_winrate: "56.74",
    wins_on_draw: "436",
    matches_on_draw: "1020",
    draw_winrate: "42.75",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "steel/emerald",
    total_matches: "1362",
    wins: "726",
    overall_winrate: "53.30",
    wins_on_play: "361",
    matches_on_play: "644",
    play_winrate: "56.06",
    wins_on_draw: "365",
    matches_on_draw: "718",
    draw_winrate: "50.84",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amethyst/sapphire",
    total_matches: "1012",
    wins: "435",
    overall_winrate: "42.98",
    wins_on_play: "257",
    matches_on_play: "511",
    play_winrate: "50.29",
    wins_on_draw: "178",
    matches_on_draw: "501",
    draw_winrate: "35.53",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "sapphire/steel",
    total_matches: "752",
    wins: "752",
    overall_winrate: "100.00",
    wins_on_play: "495",
    matches_on_play: "495",
    play_winrate: "100.00",
    wins_on_draw: "456",
    matches_on_draw: "456",
    draw_winrate: "100.00",
    mirror_matches: "752",
  },
  {
    deck: "sapphire/steel",
    versus: "sapphire/emerald",
    total_matches: "383",
    wins: "213",
    overall_winrate: "55.61",
    wins_on_play: "113",
    matches_on_play: "185",
    play_winrate: "61.08",
    wins_on_draw: "100",
    matches_on_draw: "198",
    draw_winrate: "50.51",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/ruby",
    total_matches: "332",
    wins: "175",
    overall_winrate: "52.71",
    wins_on_play: "99",
    matches_on_play: "177",
    play_winrate: "55.93",
    wins_on_draw: "76",
    matches_on_draw: "155",
    draw_winrate: "49.03",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/emerald",
    total_matches: "273",
    wins: "146",
    overall_winrate: "53.48",
    wins_on_play: "78",
    matches_on_play: "133",
    play_winrate: "58.65",
    wins_on_draw: "68",
    matches_on_draw: "140",
    draw_winrate: "48.57",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/amethyst",
    total_matches: "258",
    wins: "123",
    overall_winrate: "47.67",
    wins_on_play: "73",
    matches_on_play: "132",
    play_winrate: "55.30",
    wins_on_draw: "50",
    matches_on_draw: "126",
    draw_winrate: "39.68",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/steel",
    total_matches: "173",
    wins: "102",
    overall_winrate: "58.96",
    wins_on_play: "52",
    matches_on_play: "89",
    play_winrate: "58.43",
    wins_on_draw: "50",
    matches_on_draw: "84",
    draw_winrate: "59.52",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "amber/sapphire",
    total_matches: "132",
    wins: "57",
    overall_winrate: "43.18",
    wins_on_play: "30",
    matches_on_play: "66",
    play_winrate: "45.45",
    wins_on_draw: "27",
    matches_on_draw: "66",
    draw_winrate: "40.91",
    mirror_matches: "0",
  },
  {
    deck: "sapphire/steel",
    versus: "ruby/emerald",
    total_matches: "131",
    wins: "79",
    overall_winrate: "60.31",
    wins_on_play: "41",
    matches_on_play: "70",
    play_winrate: "58.57",
    wins_on_draw: "38",
    matches_on_draw: "61",
    draw_winrate: "62.30",
    mirror_matches: "0",
  },
];

export default async function Meta() {
  // const matchups: MatchupData[] = await matchupPerformance();
  // console.log(JSON.stringify(matchups));
  return <MetaPage data={matchups} />;
}
