interface LorcanitoBaseCard {
  type: "character" | "item" | "action" | "location";
  missingTestCase?: boolean;
  id: string;
  name: string;
  text?: string;
  flavour?: string;
  set: "TFC" | "ROF" | "ITI" | "URR" | "SSK" | "006";
  cost: number;
  color: CardColor;
  number: number;
  illustrator: string;
  inkwell?: boolean;
  characteristics: Array<Characteristics>;
  // 1.6. Types of Abilities
  // 1.6.1. There are several kinds of abilities in the Disney Lorcana TCG.
  // 1.6.1.1. Keywords are words or shortened phrases that represent a larger ability or abilities. See section 10 for the full list of
  // current keywords.
  // 1.6.1.2. Triggered abilities continuously look for a specific condition and have an effect when that condition is met.
  // Triggered abilities follow the rules in section 7.4.
  // 1.6.1.3. Activated abilities have a cost and an effect that occurs if that cost is paid. Activated abilities follow the rules in section 7.5.
  // 1.6.1.4. Static abilities are effects that are continuously active, either for a fixed length of time or for as long as the card
  // generating the effect is in play. Static abilities follow the rules in section 7.6.
  // 1.6.1.5. Replacement effects are generated by some static abilities. These replace one effect with another. Replacement
  // effects follow the rules in section 7.7.
  abilities?: unknown[] | { name?: string }[];
  rarity: CardRarity;
  // Adding this for simplicity
  strength?: number;
  lore?: number;
  willpower?: number;
  title?: string;
  moveCost?: number;
  movementDiscounts?: {
    filters: unknown[];
    amount: number;
  }[];
}

export interface LorcanitoLocationCard extends LorcanitoBaseCard {
  type: "location";
  title: string;
  lore?: number;
  moveCost: number;
  willpower: number;
  strength?: never;
}

export interface LorcanitoCharacterCard extends LorcanitoBaseCard {
  type: "character";
  title: string;
  lore: number;
  strength: number;
  cost: number;
  willpower: number;
  additionalNames?: string[];
}

export interface LorcanitoActionCard extends LorcanitoBaseCard {
  type: "action";
  title?: never;
  text: string;
}

export interface LorcanitoItemCard extends LorcanitoBaseCard {
  type: "item";
  title?: never;
  text: string;
  abilities: unknown[];
}

export type CardColor =
  | "amber"
  | "amethyst"
  | "emerald"
  | "ruby"
  | "sapphire"
  | "steel";

type CardRarity = "common" | "uncommon" | "rare" | "super_rare" | "legendary";

export type LorcanitoCard =
  | LorcanitoLocationCard
  | LorcanitoCharacterCard
  | LorcanitoActionCard
  | LorcanitoItemCard;

export type Characteristics =
  | "location"
  | "song"
  | "madrigal"
  | "racer"
  | "robot"
  | "action"
  | "hyena"
  | "item"
  | "villain"
  | "knight"
  | "dragon"
  | "tigger"
  | "seven dwarfs"
  | "pirate"
  | "detective"
  | "sorcerer"
  | "queen"
  | "puppy"
  | "titan"
  | "alien"
  | "king"
  | "mentor"
  | "inventor"
  | "fairy"
  | "captain"
  | "hero"
  | "prince"
  | "storyborn"
  | "floodborn"
  | "dreamborn"
  | "broom"
  | "ally"
  | "princess"
  | "musketeer"
  | "deity";
